version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/store/backend"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/compose/backend"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/compose/neurosynth-frontend"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5
