services:
  store_nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "82:80"

  neurostore:
    expose:
      - "8000"
    command: python -m uvicorn neurostore.core:asgi_app --host 0.0.0.0 --port 8000 --reload --reload-dir /store/backend/neurostore --log-level debug --proxy-headers --forwarded-allow-ips ${FORWARDED_ALLOW_IPS:-*}
    restart: "no"
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  store_outbox_worker:
    restart: "no"

  store_metadata_outbox_worker:
    restart: "no"

  store_release_worker:
    restart: "no"
