version: "2"
services:
  store_nginx:
    ports:
      - "80:80"

  neurostore:
    expose:
      - "8000"
    command: /usr/local/bin/gunicorn -w 1 -b :8000 neurostore.core:connexion_app --worker-class uvicorn.workers.UvicornWorker --log-level debug --timeout 300 --reload
    restart: "no"
    stdin_open: true # docker run -i
    tty: true        # docker run -t

