global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'celery'
    static_configs:
      - targets:
        - celery-exporter:9808
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    metrics_path: /metrics
    scheme: http
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: instance
      - source_labels: [__meta_dns_name]
        target_label: node

  - job_name: 'prometheus'
    static_configs:
      - targets:
        - localhost:9090
    metrics_path: /metrics
    scheme: http

  - job_name: 'grafana'
    static_configs:
      - targets:
        - grafana:3000
    metrics_path: /metrics
    scheme: http

  - job_name: 'neurovault-tasks'
    static_configs:
      - targets:
        - celery-exporter:9808
    metrics_path: /metrics
    scrape_interval: 10s
    honor_labels: true
    metric_relabel_configs:
      - source_labels: [task_name]
        regex: 'neurovault.*'
        action: keep

  - job_name: 'neurostore-tasks'
    static_configs:
      - targets:
        - celery-exporter:9808
    metrics_path: /metrics
    scrape_interval: 10s
    honor_labels: true
    metric_relabel_configs:
      - source_labels: [task_name]
        regex: 'neurostore.*'
        action: keep

# Security settings
basic_auth_users:
  prometheus: ${PROMETHEUS_PASSWORD}

tls_server_config:
  cert_file: /etc/prometheus/certs/prometheus.crt
  key_file: /etc/prometheus/certs/prometheus.key

# Storage settings
storage:
  tsdb:
    path: /prometheus
    retention:
      time: 15d
      size: 5GB
    wal:
      retention:
        time: 12h

# Query performance settings
query:
  max_samples: 50000000
  timeout: 2m
  max_concurrent: 20

# Remote write configuration (optional)
# remote_write:
#   - url: "http://remote-storage:9201/write"
#     queue_config:
#       max_samples_per_send: 10000
#       capacity: 500000
#       max_shards: 200
