import { MetaAnalysisReturn, ProjectReturn, ResultReturn } from 'neurosynth-compose-typescript-sdk';
import {
    StudysetReturn,
    StudyReturn,
    PointReturn,
    ConditionReturn,
    AnalysisReturn,
    BaseStudyReturn,
} from 'neurostore-typescript-sdk';
import { NeurostoreAnnotation } from 'utils/api';
import { IStoreStudy } from 'pages/Study/store/StudyStore.helpers';
import { INeurovault } from 'hooks/metaAnalyses/useGetNeurovaultImages';

const mockConditions: () => ConditionReturn[] = () => [
    {
        name: 'mock-condition-name-1',
        description: 'mock-condition-description-1',
        id: 'mock-condition-id-1',
        created_at: '',
        user: 'github|user-1',
    },
    {
        name: 'mock-condition-name-2',
        description: 'mock-condition-description-2',
        id: 'mock-condition-id-2',
        created_at: '',
        user: 'github|user-1',
    },
];

const mockWeights: () => number[] = () => [1, 1];

const mockPoints: () => PointReturn[] = () => [
    {
        analysis: '3MXg8tfRq2sh',
        coordinates: [12.0, -18.0, 22.0],
        created_at: '2021-11-10T19:46:43.510565+00:00',
        id: '7vVqmHtGtnkQ',
        image: null,
        kind: 'unknown',
        label_id: null,
        space: 'MNI',
        user: 'some-user',
        value: '',
        entities: [],
    },
    {
        analysis: '3MXg8tfRq2sh',
        coordinates: [-40.0, -68.0, -20.0],
        created_at: '2021-11-10T19:46:43.510565+00:00',
        id: '3fZJuzbqti5v',
        image: null,
        kind: 'unknown',
        label_id: null,
        space: 'MNI',
        user: 'some-user',
        value: '',
        entities: [],
    },
    {
        analysis: '3MXg8tfRq2sh',
        coordinates: [-10.0, -60.0, 18.0],
        created_at: '2021-11-10T19:46:43.510565+00:00',
        id: '47aqyStcBEsC',
        image: null,
        kind: 'unknown',
        label_id: null,
        space: 'MNI',
        user: 'some-user',
        value: '',
        entities: [],
    },
];

const mockStorePoints: () => PointReturn[] = () => [
    {
        analysis: '3MXg8tfRq2sh',
        created_at: '2021-11-10T19:46:43.510565+00:00',
        id: '7vVqmHtGtnkQ',
        image: null,
        kind: 'unknown',
        label_id: null,
        space: 'MNI',
        user: 'some-user',
        value: '',
        entities: [],
        x: 12,
        y: -18,
        z: 22,
    },
    {
        analysis: '3MXg8tfRq2sh',
        coordinates: [-40.0, -68.0, -20.0],
        created_at: '2021-11-10T19:46:43.510565+00:00',
        id: '3fZJuzbqti5v',
        image: null,
        kind: 'unknown',
        label_id: null,
        space: 'MNI',
        user: 'some-user',
        value: '',
        entities: [],
        x: -40,
        y: -68,
        z: -20,
    },
    {
        analysis: '3MXg8tfRq2sh',
        coordinates: [-10.0, -60.0, 18.0],
        created_at: '2021-11-10T19:46:43.510565+00:00',
        id: '47aqyStcBEsC',
        image: null,
        kind: 'unknown',
        label_id: null,
        space: 'MNI',
        user: 'some-user',
        value: '',
        entities: [],
        x: -10,
        y: -60,
        z: 18,
    },
];

const mockAnalyses: () => AnalysisReturn[] = () => [
    {
        conditions: mockConditions(),
        created_at: '2021-11-10T19:46:43.510565+00:00',
        description: null,
        id: '3MXg8tfRq2sh',
        images: [],
        name: '41544',
        points: mockPoints(),
        study: '4nz6aH7M59k2',
        user: 'some-user',
        weights: mockWeights(),
    },
    {
        conditions: [],
        created_at: '2021-11-10T19:46:43.510565+00:00',
        description: null,
        id: '6iaKVRHx8F9i',
        images: [],
        name: '41545',
        points: [],
        study: '4nz6aH7M59k2',
        user: 'some-user',
        weights: [],
    },
];

const mockStudysets: () => StudysetReturn[] = () => [
    {
        created_at: '2022-04-28T16:39:36.134359+00:00',
        id: '4eTAChpnL3Tg',
        neurostore_id: '4gUL3Zj2Kb7S',
        snapshot: null,
        updated_at: null,
        user: null,
        name: 'studyset-name-1',
        description: 'studyset-description-1',
        studies: ['4ZhkLTH8k2P6'],
    },
    {
        created_at: '2022-04-28T16:39:36.134359+00:00',
        id: '3JRewi4ND7rq',
        neurostore_id: 'wXQ9Fxw3mPz3',
        snapshot: null,
        updated_at: null,
        user: null,
        name: 'studyset-name-2',
        description: 'studyset-description-2',
        studies: [],
    },
    {
        created_at: '2022-04-28T16:39:36.134359+00:00',
        id: '88oi5AKK8aJN',
        neurostore_id: 'M8VRV2ZKMHh2',
        snapshot: null,
        updated_at: null,
        user: null,
        name: 'studyset-name-3',
        description: 'studyset-description-3',
        studies: [],
    },
];

const mockStudysetNested: () => StudysetReturn = () => ({
    created_at: '2024-02-16T20:17:48.641342+00:00',
    description: '',
    doi: null,
    id: '3tuNUkQTqxvP',
    name: 'Mock Studyset',
    pmid: null,
    publication: null,
    studies: mockStudies(),
    updated_at: null,
    user: 'github|26612023',
});

const mockStudysetNotNested: () => StudysetReturn = () => ({
    created_at: '2024-02-16T20:17:48.641342+00:00',
    description: '',
    doi: null,
    id: '3tuNUkQTqxvP',
    name: 'Mock Studyset',
    pmid: null,
    publication: null,
    studies: ['5cLR4qwokFqV', '6cbdeyacHieR'],
    updated_at: null,
    user: 'github|26612023',
});

const mockAnnotations: () => NeurostoreAnnotation[] = () => [
    {
        description: 'this is an annotation',
        user: 'github|26612023',
        name: 'choose this annotation',
        studyset: '7RWXkc9DHraB',
        updated_at: '2022-04-28T16:26:00.629711+00:00',
        source: null,
        source_id: null,
        note_keys: {
            inclusion_col: { type: 'boolean', order: 0 },
            aergegr: { type: 'number', order: 1 },
            aberg: { type: 'string', order: 2 },
        },
        metadata: null,
        id: '62RUsQpwdouU',
        source_updated_at: null,
        created_at: '2022-04-28T16:25:16.431054+00:00',
        notes: [
            {
                authors: 'Dierks T, Linden DE, Jandl M, Formisano E, Goebel R, Lanfermann H, Singer W',
                analysis: '7eEjbzRmX6wv',
                study_name: "Activation of Heschl's gyrus during auditory hallucinations.",
                note: {
                    inclusion_col: true,
                    aergegr: 1234634,
                    aberg: 'aeraerg',
                },
                study_year: 1999,
                study: '4PBKSMmuUmu6',
                publication: 'Neuron',
                analysis_name: '35712',
            },
            {
                authors: 'Dierks T, Linden DE, Jandl M, Formisano E, Goebel R, Lanfermann H, Singer W',
                analysis: '5V3pSFxGqYFm',
                study_name: "Activation of Heschl's gyrus during auditory hallucinations.",
                note: {
                    inclusion_col: true,
                    aergegr: 1234634,
                    aberg: 'aeraerg',
                },
                study_year: 1999,
                study: '4PBKSMmuUmu6',
                publication: 'Neuron',
                analysis_name: '35713',
            },
            {
                authors: 'Jueptner M, Stephan KM, Frith CD, Brooks DJ, Frackowiak RS, Passingham RE',
                analysis: '5CUdzgAYKk5h',
                study_name: 'Anatomy of motor learning. I. Frontal cortex and attention to action.',
                note: {
                    inclusion_col: true,
                    aergegr: 1234634,
                    aberg: 'aeraerg',
                },
                study_year: 1997,
                study: '6be2ke4duJvg',
                publication: 'Journal of neurophysiology',
                analysis_name: '26997',
            },
            {
                authors: 'Jueptner M, Stephan KM, Frith CD, Brooks DJ, Frackowiak RS, Passingham RE',
                analysis: '3eoGBDLj43ih',
                study_name: 'Anatomy of motor learning. I. Frontal cortex and attention to action.',
                note: {
                    inclusion_col: true,
                    aergegr: 1234634,
                    aberg: 'aeraerg',
                },
                study_year: 1997,
                study: '6be2ke4duJvg',
                publication: 'Journal of neurophysiology',
                analysis_name: '26998',
            },
            {
                authors: 'Peterson BS, Skudlarski P, Gatenby JC, Zhang H, Anderson AW, Gore JC',
                analysis: '6fCoexBvSu2m',
                study_name:
                    'An fMRI study of Stroop word-color interference: evidence for cingulate subregions subserving multiple distributed attentional systems.',
                note: {
                    inclusion_col: true,
                    aergegr: 1234634,
                    aberg: 'aeraerg',
                },
                study_year: 1999,
                study: 'DcRHerjPxKYb',
                publication: 'Biological psychiatry',
                analysis_name: '14646',
            },
        ],
    },
];

const mockStudy: (studyPropOverride?: Partial<StudyReturn>) => StudyReturn = (studyPropOverride) => ({
    source: 'neurostore',
    source_id: '7f66YLxzjPKk',
    doi: 'NaN',
    name: 'Amygdala-hippocampal involvement in human aversive trace conditioning revealed through event-related functional magnetic resonance imaging.',
    authors: 'Buchel C, Dolan RJ, Armony JL, Friston KJ',
    id: '4ZhkLTH8k2P6',
    user: 'github|26612023',
    updated_at: null,
    source_updated_at: '2022-04-28T16:23:11.548030+00:00',
    publication: 'The Journal of neuroscience : the official journal of the Society for Neuroscience',
    created_at: '2022-05-18T19:38:15.262996+00:00',
    analyses: mockAnalyses(),
    description: null,
    year: 1999,
    metadata: null,
    pmid: '10594068',
    studysets: [],
    ...(studyPropOverride || {}),
});

const mockStoreStudy: (studyPropOverride?: Partial<IStoreStudy>) => IStoreStudy = (studyPropOverride) => ({
    source: 'neurostore',
    source_id: '7f66YLxzjPKk',
    doi: 'NaN',
    name: 'Amygdala-hippocampal involvement in human aversive trace conditioning revealed through event-related functional magnetic resonance imaging.',
    authors: 'Buchel C, Dolan RJ, Armony JL, Friston KJ',
    id: '4ZhkLTH8k2P6',
    user: 'github|26612023',
    updated_at: null,
    source_updated_at: '2022-04-28T16:23:11.548030+00:00',
    publication: 'The Journal of neuroscience : the official journal of the Society for Neuroscience',
    created_at: '2022-05-18T19:38:15.262996+00:00',
    analyses: [],
    description: null,
    year: 1999,
    metadata: [],
    pmid: '10594068',
    studysets: [],
    ...(studyPropOverride || {}),
});

const mockMetaAnalyses: () => MetaAnalysisReturn[] = () => [
    {
        annotation: '6M3PvaWEmcWf',
        created_at: '2022-08-12T00:47:12.259280+00:00',
        description: 'description 1',
        id: 'iBcMmTBvr7Zh',
        name: 'name 1',
        specification: '6ovxxkKiy7Sw',
        studyset: '5ATjENA3VVyE',
        updated_at: '2022-08-12T00:48:08.734923+00:00',
        user: 'auth0|62e0e6c9dd47048572613b4d',
    },
    {
        annotation: '6M3PvaWEmcWf',
        created_at: '2022-08-11T22:32:50.176873+00:00',
        description: 'description 2',
        id: '3VQe7vJUADSH',
        name: 'name 2',
        specification: '3BXYLbPGgrfw',
        studyset: '5ATjENA3VVyE',
        updated_at: '2022-08-11T22:33:14.152328+00:00',
        user: 'github|26612023',
    },
    {
        annotation: '6M3PvaWEmcWf',
        created_at: '2022-07-25T11:10:16.112671+00:00',
        description: 'description 3',
        id: '3Mr2VPLJhptt',
        name: 'name 3',
        specification: '7zSZM9FiVGke',
        studyset: '5ATjENA3VVyE',
        updated_at: null,
        user: 'auth0|62de78bc11222b208cd022c8',
    },
];

const mockStudies: () => StudyReturn[] = () => [
    {
        updated_at: null,
        description: 'description 1',
        id: '5cLR4qwokFqV',
        source_updated_at: '2022-07-22T08:26:40.465069+00:00',
        source_id: 'AvFAAdAZ4yCw',
        publication: 'publication 1',
        year: 1999,
        metadata: null,
        source: 'neurostore',
        authors: 'list of authors 1',
        pmid: 'pmid 1',
        created_at: '2022-08-12T22:42:44.246896+00:00',
        analyses: ['4MadtF5K8Yw2', '7oQ5gRe6nWHe'],
        name: 'name 1',
        doi: 'doi 1',
        user: 'github|26612023',
    },
    {
        updated_at: null,
        description: 'description 2',
        id: '6cbdeyacHieR',
        source_updated_at: '2022-07-22T08:31:05.214847+00:00',
        source_id: '3zutS8kyg2sy',
        publication: 'publication 2',
        year: null,
        metadata: {
            url: 'https://neurovault.org/collections/2411/',
            download_url: 'https://neurovault.org/collections/2411/download',
            owner: 1274,
            contributors: 'ehtelzer',
            owner_name: 'emccormick20',
            number_of_images: 1,
            paper_url: 'http://journal.frontiersin.org/article/10.3389/fnhum.2017.00141/full',
            full_dataset_url: '',
            private: false,
            add_date: '2017-04-04T17:47:16.863092Z',
            modify_date: '2019-11-10T20:39:12.916636Z',
            doi_add_date: '2019-11-10T20:39:12.911623Z',
            type_of_design: null,
            number_of_imaging_runs: null,
            number_of_experimental_units: null,
            length_of_runs: null,
            length_of_blocks: null,
            length_of_trials: '',
            optimization: null,
            optimization_method: '',
            subject_age_mean: null,
            subject_age_min: null,
            subject_age_max: null,
            handedness: null,
            proportion_male_subjects: null,
            inclusion_exclusion_criteria: '',
            number_of_rejected_subjects: null,
            group_comparison: null,
            group_description: '',
            scanner_make: '',
            scanner_model: '',
            field_strength: null,
            pulse_sequence: '',
            parallel_imaging: '',
            field_of_view: null,
            matrix_size: null,
            slice_thickness: null,
            skip_distance: null,
            acquisition_orientation: '',
            order_of_acquisition: null,
            repetition_time: null,
            echo_time: null,
            flip_angle: null,
            software_package: '',
            software_version: '',
            order_of_preprocessing_operations: '',
            quality_control: '',
            used_b0_unwarping: null,
            b0_unwarping_software: '',
            used_slice_timing_correction: null,
            slice_timing_correction_software: '',
            used_motion_correction: null,
            motion_correction_software: '',
            motion_correction_reference: '',
            motion_correction_metric: '',
            motion_correction_interpolation: '',
            used_motion_susceptibiity_correction: null,
            used_intersubject_registration: null,
            intersubject_registration_software: '',
            intersubject_transformation_type: null,
            nonlinear_transform_type: '',
            transform_similarity_metric: '',
            interpolation_method: '',
            object_image_type: '',
            functional_coregistered_to_structural: null,
            functional_coregistration_method: '',
            coordinate_space: null,
            target_template_image: '',
            target_resolution: null,
            used_smoothing: null,
            smoothing_type: '',
            smoothing_fwhm: null,
            resampled_voxel_size: null,
            intrasubject_model_type: '',
            intrasubject_estimation_type: '',
            intrasubject_modeling_software: '',
            hemodynamic_response_function: '',
            used_temporal_derivatives: null,
            used_dispersion_derivatives: null,
            used_motion_regressors: null,
            used_reaction_time_regressor: null,
            used_orthogonalization: null,
            orthogonalization_description: '',
            used_high_pass_filter: null,
            high_pass_filter_method: '',
            autocorrelation_model: '',
            group_model_type: '',
            group_estimation_type: '',
            group_modeling_software: '',
            group_inference_type: null,
            group_model_multilevel: '',
            group_repeated_measures: null,
            group_repeated_measures_method: '',
            nutbrain_hunger_state: null,
            nutbrain_food_viewing_conditions: '',
            nutbrain_food_choice_type: '',
            nutbrain_taste_conditions: '',
            nutbrain_odor_conditions: '',
            communities: [],
        },
        source: 'neurostore',
        authors: 'list of authors 2',
        pmid: null,
        created_at: '2022-08-04T23:56:20.441846+00:00',
        analyses: ['5VFpbNNukvoY'],
        name: 'name 2',
        doi: 'doi 2',
        user: 'github|26612023',
    },
];

const mockBaseStudy: () => BaseStudyReturn = () => ({
    id: '3V8TUXsUAMna',
    user: null,
    username: null,
    created_at: '2023-06-21T22:17:27.973390+00:00',
    updated_at: '2023-08-24T14:30:22.320233+00:00',
    metadata: null,
    versions: [
        {
            id: 'LhVcFRWQnYnm',
            user: null,
            username: null,
            created_at: '2023-05-20T00:26:49.948975+00:00',
            updated_at: '2023-06-21T22:17:27.973390+00:00',
            source: 'neuroquery',
        },
    ],
    name: 'Abnormal regional homogeneity as potential imaging biomarker for psychosis risk syndrome: a resting-state fMRI study and support vector machine analysis',
    description: null,
    publication: null,
    doi: null,
    pmid: '27272341',
    pmcid: null,
    authors: null,
    year: null,
    level: 'group',
});

const mockProject: () => ProjectReturn = () => ({
    created_at: '2024-05-17T17:32:41.215440+00:00',
    description: 'New project generated from files: nback-Owen-ALL-Updated copy.txt',
    draft: true,
    id: '5WSN3nu6hMjj',
    meta_analyses: [],
    name: 'Untitled sleuth project',
    neurostore_study: {
        created_at: '2024-05-17T17:32:41.224351+00:00',
        exception: null,
        neurostore_id: 'RZAu78WPLgay',
        status: 'PENDING',
        traceback: null,
        updated_at: '2024-05-17T17:32:41.229632+00:00',
    },
    neurostore_url: 'https://neurostore.org/api/studies/RZAu78WPLgay',
    provenance: {
        curationMetadata: {
            columns: [
                {
                    id: 'ad1cbff6-d95d-4576-ac99-8ea2f7e1b395',
                    name: 'not included',
                    stubStudies: [],
                },
                {
                    id: '8525c03a-f47b-4ee0-9a59-9cbde5ab0690',
                    name: 'included',
                    stubStudies: [
                        {
                            abstractText: '',
                            articleLink: '',
                            articleYear: '2',
                            authors: 'Ragland J D,',
                            doi: '10.1037/0894-4105.16.3.370',
                            exclusionTagId: null,
                            id: '277d4844-60e1-48c8-9a42-3b46ff4c9e64',
                            identificationSource: {
                                id: 'neurosynth_sleuth_id_source',
                                label: 'Sleuth',
                            },
                            journal: '',
                            keywords: '',
                            neurostoreId: '6Lz4BqniENMA',
                            pmcid: '',
                            pmid: '',
                            searchTerm: '',
                            tags: [
                                {
                                    id: 'd82a9992-640f-45f7-b81b-ce2d7b7a49ee',
                                    isAssignable: true,
                                    isExclusionTag: false,
                                    label: 'nback-Owen-ALL-Updated copy.txt',
                                },
                            ],
                            title: '',
                        },
                        {
                            abstractText: '',
                            articleLink: '',
                            articleYear: '2',
                            authors: 'Rama P,',
                            doi: '10.1006/nimg.2001.0777',
                            exclusionTagId: null,
                            id: 'b9f6b007-65c2-46f4-8f54-b59c759de152',
                            identificationSource: {
                                id: 'neurosynth_sleuth_id_source',
                                label: 'Sleuth',
                            },
                            journal: '',
                            keywords: '',
                            neurostoreId: '4QC9ff3c4seH',
                            pmcid: '',
                            pmid: '',
                            searchTerm: '',
                            tags: [
                                {
                                    id: 'd82a9992-640f-45f7-b81b-ce2d7b7a49ee',
                                    isAssignable: true,
                                    isExclusionTag: false,
                                    label: 'nback-Owen-ALL-Updated copy.txt',
                                },
                            ],
                            title: '',
                        },
                        {
                            abstractText: '',
                            articleLink: '',
                            articleYear: '1',
                            authors: 'Schumacher E H,',
                            doi: '10.1006/nimg.1996.0009',
                            exclusionTagId: null,
                            id: 'e10e6c55-095b-4a90-9032-ea86ccf93fb1',
                            identificationSource: {
                                id: 'neurosynth_sleuth_id_source',
                                label: 'Sleuth',
                            },
                            journal: '',
                            keywords: '',
                            neurostoreId: '7VhHUNpiyvxN',
                            pmcid: '',
                            pmid: '',
                            searchTerm: '',
                            tags: [
                                {
                                    id: 'd82a9992-640f-45f7-b81b-ce2d7b7a49ee',
                                    isAssignable: true,
                                    isExclusionTag: false,
                                    label: 'nback-Owen-ALL-Updated copy.txt',
                                },
                            ],
                            title: '',
                        },
                        {
                            abstractText: '',
                            articleLink: '',
                            articleYear: '1',
                            authors: 'Smith E E,',
                            doi: '10.1093/cercor/6.1.11',
                            exclusionTagId: null,
                            id: 'a4c7e222-9b0e-49a9-aca1-8fe70dc50645',
                            identificationSource: {
                                id: 'neurosynth_sleuth_id_source',
                                label: 'Sleuth',
                            },
                            journal: '',
                            keywords: '',
                            neurostoreId: '4puK5CWhPf3n',
                            pmcid: '',
                            pmid: '',
                            searchTerm: '',
                            tags: [
                                {
                                    id: 'd82a9992-640f-45f7-b81b-ce2d7b7a49ee',
                                    isAssignable: true,
                                    isExclusionTag: false,
                                    label: 'nback-Owen-ALL-Updated copy.txt',
                                },
                            ],
                            title: '',
                        },
                    ],
                },
            ],
            exclusionTags: [
                {
                    id: 'neurosynth_exclude_exclusion',
                    isAssignable: true,
                    isExclusionTag: true,
                    label: 'Exclude',
                },
                {
                    id: 'neurosynth_duplicate_exclusion',
                    isAssignable: true,
                    isExclusionTag: true,
                    label: 'Duplicate',
                },
            ],
            identificationSources: [
                {
                    id: 'neurosynth_neurostore_id_source',
                    label: 'Neurostore',
                },
                {
                    id: 'neurosynth_pubmed_id_source',
                    label: 'PubMed',
                },
                {
                    id: 'neurosynth_scopus_id_source',
                    label: 'Scopus',
                },
                {
                    id: 'neurosynth_web_of_science_id_source',
                    label: 'Web of Science',
                },
                {
                    id: 'neurosynth_psycinfo_id_source',
                    label: 'PsycInfo',
                },
                {
                    id: 'neurosynth_sleuth_id_source',
                    label: 'Sleuth',
                },
            ],
            infoTags: [
                {
                    id: 'neurosynth_untagged_tag',
                    isAssignable: false,
                    isExclusionTag: false,
                    label: 'Untagged studies',
                },
                {
                    id: 'neurosynth_uncategorized_tag',
                    isAssignable: false,
                    isExclusionTag: false,
                    label: 'Uncategorized Studies',
                },
                {
                    id: 'neurosynth_needs_review_tag',
                    isAssignable: false,
                    isExclusionTag: false,
                    label: 'Needs Review',
                },
            ],
            prismaConfig: {
                eligibility: {
                    exclusionTags: [],
                },
                identification: {
                    exclusionTags: [],
                },
                isPrisma: false,
                screening: {
                    exclusionTags: [],
                },
            },
        },
        extractionMetadata: {
            annotationId: '3EkUXiRFc7sL',
            studyStatusList: [
                {
                    id: '6YFH5BnHRDeR',
                    status: 'completed',
                },
                {
                    id: '5U3FRksVuHZ8',
                    status: 'completed',
                },
                {
                    id: '6yiES7GyNLH3',
                    status: 'completed',
                },
                {
                    id: '4XqQxkeQ8bH7',
                    status: 'completed',
                },
            ],
            studysetId: '3jTnjw8EiJMs',
        },
        metaAnalysisMetadata: {
            canEditMetaAnalyses: true,
        },
    },
    public: true,
    updated_at: null,
    user: 'some-github-user',
    username: 'Nicholas Lee',
});

const mockMetaAnalysisResult: () => ResultReturn = () => ({
    cli_args: null,
    cli_version: null,
    created_at: '2024-12-06T01:14:37.069129+00:00',
    diagnostic_table:
        'id\tPositiveTail 1\tPositiveTail 2\tPositiveTail 3\tPositiveTail 4\tPositiveTail 5\tPositiveTail 6\tPositiveTail 7\tPositiveTail 8\tPositiveTail 9\tPositiveTail 10\tPositiveTail 11\tPositiveTail 12\tPositiveTail 13\tPositiveTail 14\tPositiveTail 15\tPositiveTail 16\tPositiveTail 17\tPositiveTail 18\tPositiveTail 19\tPositiveTail 20\tPositiveTail 21\tPositiveTail 22\tPositiveTail 23\tPositiveTail 24\tPositiveTail 25\tPositiveTail 26\tPositiveTail 27\tPositiveTail 28\nA_Preliminary_Study_of_Functional_Brain_Activation_among_Marijuana_Users_during_Performance_of_a_Virtual_Water_Maze_Task-tab3;_tab4\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nAberrant_Orbitofrontal_Connectivity_in_Marijuana_Smoking_Youths-T4;_T2;_T3;_T5\t4\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\nAbnormal_brain_activity_in_prefrontal_brain_regions_in_abstinent_marijuana_users-tbl2\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nAbstinent_adolescent_marijuana_users_show_altered_fMRI_response_during_spatial_working_memory-tbl2;_T2\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nAge_of_onset_of_marijuana_use_impacts_inhibitory_processing.-37953;_111;_222;_333\t13\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nAltered_affective_response_in_marijuana_smokers:_an_FMRI_study.-21259;_21262;_21260;_21261;_21263\t4\t0\t0\t0\t0\t0\t0\t4\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nAltered_brain_tissue_composition_in_heavy_marijuana_users.-21242;_21243\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nAltered_prefrontal_and_insular_cortical_thickness_in_adolescent_marijuana_users.-14325;_some_new_analysis\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nBrain_activation_to_negative_stimuli_mediates_a_relationship_between_adolescent_marijuana_use_and_later_emotional_functioning.-POS:_Heavy_Users_>_Controls;_POS:_Controls_>_Heavy_Users;_NEG:_Controls_>_Heavy_Users\t0\t0\t0\t0\t0\t0\t0\t2\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nCiticoline_Treatment_Improves_Measures_of_Impulsivity_and_Task_Performance_in_Chronic_Marijuana_Smokers:_A_Pilot_BOLD_fMRI_Study-T3;_T2\t6\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t2\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nCortico-cerebellar_abnormalities_in_adolescents_with_heavy_marijuana_use.-41239\t1\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nEffects_of_prenatal_marijuana_on_visuospatial_working_memory:_An_fMRI_study_in_young_adults-tbl3\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nFunctional_Activation_and_Effective_Connectivity_Differences_in_Adolescent_Marijuana_Users_Performing_a_Simulated_Gambling_Task-tab3;_tab4\t3\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nFunctional_imaging_of_implicit_marijuana_associations_during_performance_on_an_Implicit_Association_Test_(IAT).-14429;_14430\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nIndividual_and_Additive_Effects_of_the_CNR1_and_FAAH_Genes_on_Brain_Response_to_Marijuana_Cues-tbl3;_tbl2\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nMarijuana_craving_in_the_brain.-40708;_40709\t3\t2\t0\t1\t0\t0\t0\t2\t0\t0\t2\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nMarijuana_use_is_associated_with_a_reorganized_visual-attention_network_and_cerebellar_hypoactivation.-15660;_15661\t2\t2\t0\t1\t1\t1\t0\t1\t0\t0\t0\t1\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nNeural_Correlates_of_Verbal_Learning_in_Adolescent_Alcohol_and_Marijuana_Users-T3;_T2\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nNeural_Effects_of_Positive_and_Negative_Incentives_during_Marijuana_Withdrawal-pone-0061470-t005;_pone-0061470-t004;_pone-0061470-t003;_pone-0061470-t002\t7\t2\t0\t1\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nNeural_mechanisms_of_risky_decision_making_in_adolescents_reporting_frequent_alcohol_and/or_marijuana_use.-Linear_Control_>_Linear_Risk;_Mean_Control_>_Mean_Risk;_Linear_Risk_>_Linear_Control;_Mean_risk_>_Mean_control;_Mean_Risk_>_Mean_Control;_Linear_risk_>_Linear_control\t1\t2\t0\t1\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nNeural_substrates_of_faulty_decision-making_in_abstinent_marijuana_users-tbl4;_tbl3;_tbl5;_tbl2\t0\t1\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nNeuroimaging_of_marijuana_smokers_during_inhibitory_processing:_a_pilot_investigation.-20295;_111;_222;_333;_20294;_20293\t8\t0\t0\t0\t2\t0\t0\t0\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nPoor_decision-making_by_chronic_marijuana_users_is_associated_with_decreased_functional_responsiveness_to_negative_consequences-LOSS_EVALUATION;_ALL_EVALUATION\t2\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\nPreliminary_findings_demonstrating_latent_effects_of_early_adolescent_marijuana_use_onset_on_cortical_architecture.-21176;_my_new_analysis\t0\t2\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nThe_impact_of_initiation:_Early_onset_marijuana_smokers_demonstrate_altered_Stroop_performance_and_brain_activation-tbl0025;_T5\t2\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t2\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nWhite_matter_characterization_of_adolescent_binge_drinking_with_and_without_co-occurring_marijuana_use:_A_3-year_investigation-t0010\t0\t0\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nfMRI_BOLD_Response_in_High-risk_College_Students_(Part_1):_During_Exposure_to_Alcohol,_Marijuana,_Polydrug_and_Emotional_Picture_Cues-AGQ042TB1;_AGQ042TB2\t3\t0\t2\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nfMRI_BOLD_Response_of_High-risk_College_Students_(Part_2):_During_Memory_Priming_of_Alcohol,_Marijuana_and_Polydrug_Picture_Cues-Marijuana_non-studied_>_marijuana_studied;_Polydrug_non-studied_>_polydrug_studied;_Alcohol_non-studied_>_alcohol_studied\t0\t2\t0\t0\t1\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\nfMRI_response_to_spatial_working_memory_in_adolescents_with_comorbid_marijuana_and_alcohol_use_disorders.-21243\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\n',
    id: 'PyftC25kGRm5',
    meta_analysis_id: 'WfCnGvpZxXi4',
    neurovault_collection: {
        collection_id: '19125',
        created_at: '2024-12-06T01:14:37.119322+00:00',
        files: [
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894952',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.571618+00:00',
                url: 'https://neurovault.org/api/images/894952',
            },
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894953',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.560317+00:00',
                url: 'https://neurovault.org/api/images/894953',
            },
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894954',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.583886+00:00',
                url: 'https://neurovault.org/api/images/894954',
            },
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894955',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.572714+00:00',
                url: 'https://neurovault.org/api/images/894955',
            },
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894956',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.626910+00:00',
                url: 'https://neurovault.org/api/images/894956',
            },
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894959',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.572475+00:00',
                url: 'https://neurovault.org/api/images/894959',
            },
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894963',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.593230+00:00',
                url: 'https://neurovault.org/api/images/894963',
            },
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894964',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.616257+00:00',
                url: 'https://neurovault.org/api/images/894964',
            },
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894958',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.622045+00:00',
                url: 'https://neurovault.org/api/images/894958',
            },
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894957',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.593275+00:00',
                url: 'https://neurovault.org/api/images/894957',
            },
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894960',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.581951+00:00',
                url: 'https://neurovault.org/api/images/894960',
            },
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894962',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.614241+00:00',
                url: 'https://neurovault.org/api/images/894962',
            },
            {
                created_at: '2024-12-06T01:14:38.323194+00:00',
                exception: null,
                image_id: '894961',
                status: 'OK',
                updated_at: '2024-12-06T01:14:38.617741+00:00',
                url: 'https://neurovault.org/api/images/894961',
            },
        ],
        updated_at: null,
        url: 'https://neurovault.org/api/collections/19125',
    },
    updated_at: '2024-12-06T01:14:38.323194+00:00',
});

const mockNeurovault: () => INeurovault[] = () => [
    {
        url: 'http://neurovault.org/images/894952/',
        id: 894952,
        file: 'http://neurovault.org/media/images/19125/p_desc-uniformity.nii.gz',
        collection: 'http://neurovault.org/collections/19125/',
        collection_id: 19125,
        file_size: 177268,
        cognitive_paradigm_cogatlas: null,
        cognitive_paradigm_cogatlas_id: null,
        cognitive_contrast_cogatlas: null,
        cognitive_contrast_cogatlas_id: null,
        map_type: 'P map (given null hypothesis)',
        analysis_level: 'meta-analysis',
        name: 'p_desc-uniformity.nii.gz',
        description: '',
        add_date: '2024-12-06T02:14:39.317726+01:00',
        modify_date: '2024-12-06T02:14:43.836661+01:00',
        is_valid: true,
        surface_left_file: 'http://neurovault.org/media/images/19125/894952.L.func.gii',
        surface_right_file: 'http://neurovault.org/media/images/19125/894952.R.func.gii',
        data_origin: 'volume',
        target_template_image: 'GenericMNI',
        subject_species: 'homo sapiens',
        figure: null,
        handedness: null,
        age: null,
        gender: null,
        race: null,
        ethnicity: null,
        BMI: null,
        fat_percentage: null,
        waist_hip_ratio: null,
        mean_PDS_score: null,
        tanner_stage: null,
        days_since_menstruation: null,
        hours_since_last_meal: null,
        bis_bas_score: null,
        spsrq_score: null,
        bis11_score: null,
        thumbnail: 'http://neurovault.org/media/images/19125/glass_brain_894952.jpg',
        reduced_representation: null,
        is_thresholded: false,
        perc_bad_voxels: 74.68694225423734,
        not_mni: false,
        brain_coverage: 100.0,
        perc_voxels_outside: 0.0,
        number_of_subjects: null,
        modality: 'Other',
        statistic_parameters: null,
        smoothness_fwhm: null,
        contrast_definition: null,
        contrast_definition_cogatlas: null,
        cognitive_paradigm_description_url: null,
        image_type: 'statistic_map',
    },
];

const mockMetaAnalysisReturn: () => MetaAnalysisReturn = () => ({
    cached_annotation: 'Q7PGxaTr6Ke4',
    cached_studyset: 'Ue5rb87H4nMi',
    created_at: '2024-12-06T01:07:18.120143+00:00',
    description: 'MKDAChi2 meta analysis with FDRCorrector',
    id: 'WfCnGvpZxXi4',
    name: 'My new test MKDAChi2 Meta Analysis: included',
    neurostore_analysis: {
        created_at: '2024-12-06T01:07:18.146325+00:00',
        exception: null,
        id: 'nBC95wqsJgYM',
        neurostore_id: 'zyWsKHSiU3Y6',
        status: 'OK',
        traceback: null,
        updated_at: '2024-12-06T01:14:42.206629+00:00',
    },
    neurostore_url: 'https://neurostore.org/api/analyses/zyWsKHSiU3Y6',
    project: '5fuUb89eACzZ',
    provenance: null,
    results: [
        {
            created_at: '2024-12-06T01:14:37.069129+00:00',
            id: 'PyftC25kGRm5',
            updated_at: '2024-12-06T01:14:38.323194+00:00',
        },
    ],
    run_key: 'oXsfHh0RyA0jFRzQdhwyLA',
    specification: {
        conditions: [true],
        corrector: {
            args: {
                alpha: 0.05,
                method: 'indep',
            },
            type: 'FDRCorrector',
        },
        created_at: '2024-12-06T01:07:17.495976+00:00',
        database_studyset: 'neurostore',
        estimator: {
            args: {
                '**kwargs': {},
                kernel__r: 10,
                kernel__value: 1,
                prior: 0.5,
            },
            type: 'ALE',
        },
        filter: 'included',
        id: 'h57xeSmdQcpj',
        type: 'CBMA',
        updated_at: null,
        user: 'github|26612023',
        username: 'Nicholas Lee',
        weights: [1.0],
    },
    studyset: {
        created_at: '2024-12-06T01:07:17.670624+00:00',
        id: 'Ue5rb87H4nMi',
        neurostore_id: '7WRDwR5YfnBg',
        snapshot: {
            snapshot: {
                created_at: '2023-12-12T22:33:20.849705+00:00',
                description: 'my test description',
                doi: null,
                id: '7WRDwR5YfnBg',
                name: 'Studyset for My new test',
                pmid: null,
                publication: null,
                studies: [
                    {
                        analyses: [
                            {
                                conditions: [],
                                description: 'Table 2',
                                id: '3GTqJytpC3p6',
                                images: [],
                                metadata: null,
                                name: 'Linear Control > Linear Risk',
                                points: [
                                    {
                                        coordinates: [-40.0, -26.0, 50.0],
                                        id: '9Jzj2X5DxaiL',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 7.49,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-4.0, 0.0, 54.0],
                                        id: '44G9cjh3T9mY',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 4.93,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-44.0, -34.0, 16.0],
                                        id: '54rAqeX2Vp54',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 5.29,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [28.0, -88.0, -6.0],
                                        id: '7dRbckNiNd35',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 4.59,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [58.0, -20.0, 38.0],
                                        id: 'sDcbvTeisgcb',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 4.52,
                                            },
                                        ],
                                    },
                                ],
                                user: 'github|26612023',
                                weights: [],
                            },
                            {
                                conditions: [],
                                description: 'Table 2',
                                id: '3GzSVjE8mrS3',
                                images: [],
                                metadata: null,
                                name: 'Mean Control > Mean Risk',
                                points: [
                                    {
                                        coordinates: [12.0, -76.0, -2.0],
                                        id: '3iiUJ9Gjvzns',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 13.0,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-48.0, -64.0, 40.0],
                                        id: 'AXczqpqehb2a',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 14.4,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [56.0, -56.0, 24.0],
                                        id: '3iVGLscyGBNf',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 15.2,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-42.0, 14.0, 46.0],
                                        id: '6sRLCc7AeMh7',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 12.7,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-48.0, 34.0, -2.0],
                                        id: '4CjUGeWd32fj',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 12.8,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [50.0, 38.0, -8.0],
                                        id: '85VnuggANrMU',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 12.5,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [14.0, 56.0, 30.0],
                                        id: '43NQ8JqFyPaS',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 11.8,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [6.0, -46.0, 34.0],
                                        id: '5wT3cSjqjB5s',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 12.4,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-6.0, -54.0, -46.0],
                                        id: '8EmpBr8WEJue',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 15.0,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-52.0, -8.0, -32.0],
                                        id: '5URbwza34r3b',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 9.22,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [4.0, 44.0, 50.0],
                                        id: '6k2FKbvTDzga',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 9.03,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-64.0, -14.0, -22.0],
                                        id: '7tTvbLAx9uLF',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Z',
                                                value: 9.02,
                                            },
                                        ],
                                    },
                                ],
                                user: 'github|26612023',
                                weights: [],
                            },
                        ],
                        authors: 'Claus ED, Feldstein Ewing SW, Magnan RE, Montanaro E, Hutchison KE, Bryan AD',
                        created_at: '2023-11-02T18:11:08.811383+00:00',
                        description: 'a',
                        doi: '10.1007/s11682-017-9723-x',
                        id: '5FYoyH8Z6spR',
                        metadata: {
                            sample_size: null,
                        },
                        name: 'Neural mechanisms of risky decision making in adolescents reporting frequent alcohol and/or marijuana use.',
                        pmid: '28429160',
                        publication: 'Brain imaging and behavior',
                        source: 'neurostore',
                        source_id: '3sCo5xAjxL56',
                        source_updated_at: '2023-06-21T22:17:27.973390+00:00',
                        updated_at: '2023-12-12T22:37:21.933193+00:00',
                        user: 'github|26612023',
                        year: 2018,
                    },
                    {
                        analyses: [
                            {
                                conditions: [],
                                description: null,
                                id: '3CNaH5frhTpr',
                                images: [],
                                metadata: null,
                                name: '21176',
                                points: [
                                    {
                                        coordinates: [19.0, -69.0, -7.0],
                                        id: '7NnSEQ6fug6e',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'TAL',
                                        values: [
                                            {
                                                kind: 'R',
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-23.0, 53.0, 10.0],
                                        id: '82N6ePiAWSRF',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'TAL',
                                        values: [
                                            {
                                                kind: 'R',
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [39.0, 30.0, 18.0],
                                        id: '7yRw6zhEf68M',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'TAL',
                                        values: [
                                            {
                                                kind: 'R',
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [6.0, 47.0, -20.0],
                                        id: '5wGDBHUMP5uA',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'TAL',
                                        values: [
                                            {
                                                kind: 'R',
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-44.0, -62.0, 44.0],
                                        id: '3LA2X7RYmoBE',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'TAL',
                                        values: [
                                            {
                                                kind: 'R',
                                                value: null,
                                            },
                                        ],
                                    },
                                ],
                                user: 'github|26612023',
                                weights: [],
                            },
                            {
                                conditions: [],
                                description: '',
                                id: 'CCKyTeh7jAef',
                                images: [],
                                metadata: null,
                                name: 'my new analysis',
                                points: [
                                    {
                                        coordinates: [39.0, 30.0, 18.0],
                                        id: '62e887hWm5ZL',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Pa',
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [19.0, -69.0, -7.0],
                                        id: '6C3CKPxUTYkz',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Pa',
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-23.0, 53.0, 10.0],
                                        id: 'btjdW4osrdzp',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: 'Pa',
                                                value: null,
                                            },
                                        ],
                                    },
                                ],
                                user: 'github|26612023',
                                weights: [],
                            },
                        ],
                        authors: 'Filbey FM, McQueeny T, DeWitt SJ, Mishra V',
                        created_at: '2023-10-28T19:46:16.482780+00:00',
                        description: null,
                        doi: '10.1016/j.dcn.2015.10.001',
                        id: '7wPrisH4DHmk',
                        metadata: {
                            sample_size: null,
                        },
                        name: 'Preliminary findings demonstrating latent effects of early adolescent marijuana use onset on cortical architecture.',
                        pmid: '26507433',
                        publication: 'Developmental cognitive neuroscience',
                        source: 'neurostore',
                        source_id: 'nQGt73k3CGfk',
                        source_updated_at: '2023-06-21T22:17:27.973390+00:00',
                        updated_at: '2023-10-28T19:46:17.327351+00:00',
                        user: 'github|26612023',
                        year: 2015,
                    },
                    {
                        analyses: [
                            {
                                conditions: [],
                                description: null,
                                id: '33KzpLpKDd95',
                                images: [],
                                metadata: null,
                                name: '21242',
                                points: [
                                    {
                                        coordinates: [2.0, -12.0, 0.0],
                                        id: '6Sd3Vj9WV8JX',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: null,
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [28.0, -30.0, 56.0],
                                        id: 'gVJc4wYW2VR3',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: null,
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [22.0, -18.0, -10.0],
                                        id: '6oiQFsHc9ELB',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: null,
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-20.0, -48.0, 64.0],
                                        id: '6VACn9idtiki',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: 'MNI',
                                        values: [
                                            {
                                                kind: null,
                                                value: null,
                                            },
                                        ],
                                    },
                                ],
                                user: 'github|26612023',
                                weights: [],
                            },
                            {
                                conditions: [],
                                description: '',
                                id: 't3kwfKCSnvyz',
                                images: [],
                                metadata: null,
                                name: '21243',
                                points: [
                                    {
                                        coordinates: [-46.0, -6.0, -30.0],
                                        id: '4sWCWDJf9qAt',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: null,
                                        values: [
                                            {
                                                kind: null,
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [10.0, -20.0, -24.0],
                                        id: 'NWRFLyMDWRHA',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: null,
                                        values: [
                                            {
                                                kind: null,
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [18.0, -8.0, -8.0],
                                        id: '3VvqKwJiah35',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: null,
                                        values: [
                                            {
                                                kind: null,
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-22.0, -24.0, -8.0],
                                        id: '5wd4n7Tgs7G6',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: null,
                                        values: [
                                            {
                                                kind: null,
                                                value: null,
                                            },
                                        ],
                                    },
                                    {
                                        coordinates: [-32.0, -30.0, 58.0],
                                        id: '5pkJZQKbinpp',
                                        image: null,
                                        kind: null,
                                        label_id: null,
                                        space: null,
                                        values: [
                                            {
                                                kind: null,
                                                value: null,
                                            },
                                        ],
                                    },
                                ],
                                user: 'github|26612023',
                                weights: [],
                            },
                        ],
                        authors: 'Matochik JA, Eldreth DA, Cadet JL, Bolla KI',
                        created_at: '2023-11-02T17:34:59.386691+00:00',
                        description: null,
                        doi: '10.1016/j.drugalcdep.2004.06.011',
                        id: '5KPoXYmpNbwf',
                        metadata: {
                            sample_size: null,
                        },
                        name: 'Altered brain tissue composition in heavy marijuana users.',
                        pmid: '15607838',
                        publication: 'Drug and alcohol dependence',
                        source: 'neurostore',
                        source_id: '4taREaBkeuBY',
                        source_updated_at: '2023-06-21T22:17:27.973390+00:00',
                        updated_at: '2023-11-02T17:35:00.317618+00:00',
                        user: 'github|26612023',
                        year: 2005,
                    },
                ],
                updated_at: null,
                user: 'github|26612023',
            },
        },
        updated_at: '2024-12-06T01:14:37.069129+00:00',
        url: 'https://neurostore.org/api/studysets/7WRDwR5YfnBg',
        user: 'github|26612023',
        username: 'Nicholas Lee',
        version: null,
    },
});

export {
    mockConditions,
    mockWeights,
    mockAnalyses,
    mockStudysets,
    mockAnnotations,
    mockStudy,
    mockPoints,
    mockMetaAnalyses,
    mockStudies,
    mockStudysetNested,
    mockStudysetNotNested,
    mockBaseStudy,
    mockStorePoints,
    mockStoreStudy,
    mockProject,
    mockMetaAnalysisResult,
    mockNeurovault,
    mockMetaAnalysisReturn,
};
