"""empty message

Revision ID: 0563a23d63eb
Revises: 4c6c2af3c093
Create Date: 2025-10-13 17:52:05.798922

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import neurostore.models.migration_types
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM as PGEnum

# revision identifiers, used by Alembic.
revision = '0563a23d63eb'
down_revision = '4c6c2af3c093'
branch_labels = None
depends_on = None

# When using sa.Enum in migration, set create_type=False to avoid duplicate CREATE TYPE
status_enum = PGEnum("SUCCESS", "FAILURE", "ERROR", "UNKNOWN",
                     name="status_enum", create_type=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_embeddings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('config_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_study_id', sa.Text(), nullable=True),
    sa.Column('date_executed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', status_enum, nullable=True),
    sa.Column('embedding', neurostore.models.migration_types.VectorType(), nullable=False),
    sa.ForeignKeyConstraint(['base_study_id'], ['base_studies.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['pipeline_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'config_id'),
    postgresql_partition_by='LIST (config_id)'
    )
    with op.batch_alter_table('pipeline_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_embeddings_base_study_id'), ['base_study_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_embeddings_config_id'), ['config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_embeddings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_embeddings_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('pipeline_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_embeddings', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('embedding_dimensions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_configs', schema=None) as batch_op:
        batch_op.drop_column('embedding_dimensions')
        batch_op.drop_column('has_embeddings')

    with op.batch_alter_table('pipeline_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_embeddings_updated_at'))
        batch_op.drop_index(batch_op.f('ix_pipeline_embeddings_created_at'))
        batch_op.drop_index(batch_op.f('ix_pipeline_embeddings_config_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_embeddings_base_study_id'))

    op.drop_table('pipeline_embeddings')
    # ### end Alembic commands ###
