"""empty message

Revision ID: 0deecb4a026b
Revises: 5620f4c0981a
Create Date: 2023-10-04 13:35:18.455953

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.sql import expression
import neurostore.models.migration_types


# revision identifiers, used by Alembic.
revision = '0deecb4a026b'
down_revision = '5620f4c0981a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_studies', sa.Column('has_coordinates', sa.Boolean(), server_default=expression.false(), nullable=False))
    op.add_column('base_studies', sa.Column('has_images', sa.Boolean(), server_default=expression.false(), nullable=False))
    op.add_column('studysets', sa.Column('__ts_vector__', neurostore.models.migration_types.TSVector(), sa.Computed("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=True))
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('studysets', '__ts_vector__')
    op.drop_column('base_studies', 'has_images')
    op.drop_column('base_studies', 'has_coordinates')
    # ### end Alembic commands ###
