"""empty message

Revision ID: 43b6caa42fae
Revises: 6238aa82fe93
Create Date: 2023-06-23 03:07:02.747019

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import neurostore.models.migration_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43b6caa42fae'
down_revision = '6238aa82fe93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_studies',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('publication', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('pmid', sa.String(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('__ts_vector__', neurostore.models.migration_types.TSVector(), sa.Computed("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=True),
    sa.CheckConstraint("level IN ('group', 'meta')"),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi', 'pmid', name='doi_pmid')
    )
    op.create_index(op.f('ix_base_studies_authors'), 'base_studies', ['authors'], unique=False)
    op.create_index(op.f('ix_base_studies_doi'), 'base_studies', ['doi'], unique=False)
    op.create_index(op.f('ix_base_studies_id'), 'base_studies', ['id'], unique=False)
    op.create_index(op.f('ix_base_studies_pmid'), 'base_studies', ['pmid'], unique=False)
    op.create_index(op.f('ix_base_studies_publication'), 'base_studies', ['publication'], unique=False)
    op.create_index(op.f('ix_base_studies_user_id'), 'base_studies', ['user_id'], unique=False)
    op.create_index(op.f('ix_base_studies_year'), 'base_studies', ['year'], unique=False)
    op.create_index('ix_base_study___ts_vector__', 'base_studies', ['__ts_vector__'], unique=False, postgresql_using='gin')
    op.add_column('studies', sa.Column('base_study_id', sa.Text(), nullable=True))
    op.add_column('studies', sa.Column('__ts_vector__', neurostore.models.migration_types.TSVector(), sa.Computed("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=True))
    op.create_index(op.f('ix_studies_authors'), 'studies', ['authors'], unique=False)
    op.create_index(op.f('ix_studies_doi'), 'studies', ['doi'], unique=False)
    op.create_index(op.f('ix_studies_pmid'), 'studies', ['pmid'], unique=False)
    op.create_index(op.f('ix_studies_publication'), 'studies', ['publication'], unique=False)
    op.create_index(op.f('ix_studies_source'), 'studies', ['source'], unique=False)
    op.create_index(op.f('ix_studies_source_id'), 'studies', ['source_id'], unique=False)
    op.create_index(op.f('ix_studies_user_id'), 'studies', ['user_id'], unique=False)
    op.create_index(op.f('ix_studies_year'), 'studies', ['year'], unique=False)
    op.create_index('ix_study___ts_vector__', 'studies', ['__ts_vector__'], unique=False, postgresql_using='gin')
    op.create_foreign_key(None, 'studies', 'base_studies', ['base_study_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studies', type_='foreignkey')
    op.drop_index('ix_study___ts_vector__', table_name='studies', postgresql_using='gin')
    op.drop_index(op.f('ix_studies_year'), table_name='studies')
    op.drop_index(op.f('ix_studies_user_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_source_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_source'), table_name='studies')
    op.drop_index(op.f('ix_studies_publication'), table_name='studies')
    op.drop_index(op.f('ix_studies_pmid'), table_name='studies')
    op.drop_index(op.f('ix_studies_doi'), table_name='studies')
    op.drop_index(op.f('ix_studies_authors'), table_name='studies')
    op.drop_column('studies', '__ts_vector__')
    op.drop_column('studies', 'base_study_id')
    op.drop_index('ix_base_study___ts_vector__', table_name='base_studies', postgresql_using='gin')
    op.drop_index(op.f('ix_base_studies_year'), table_name='base_studies')
    op.drop_index(op.f('ix_base_studies_user_id'), table_name='base_studies')
    op.drop_index(op.f('ix_base_studies_publication'), table_name='base_studies')
    op.drop_index(op.f('ix_base_studies_pmid'), table_name='base_studies')
    op.drop_index(op.f('ix_base_studies_id'), table_name='base_studies')
    op.drop_index(op.f('ix_base_studies_doi'), table_name='base_studies')
    op.drop_index(op.f('ix_base_studies_authors'), table_name='base_studies')
    op.drop_table('base_studies')
    # ### end Alembic commands ###
