"""empty message

Revision ID: 44d21cfa3b0e
Revises: 36a65cea101c
Create Date: 2022-10-04 14:33:31.016376

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '44d21cfa3b0e'
down_revision = '36a65cea101c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_conditions_analysis_id'), 'analysis_conditions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_conditions_condition_id'), 'analysis_conditions', ['condition_id'], unique=False)
    op.create_index(op.f('ix_annotation_analyses_analysis_id'), 'annotation_analyses', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_annotation_analyses_annotation_id'), 'annotation_analyses', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_annotations_id'), 'annotations', ['id'], unique=False)
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_point_values_id'), 'point_values', ['id'], unique=False)
    op.create_index(op.f('ix_points_id'), 'points', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_studies_id'), 'studies', ['id'], unique=False)
    op.create_index(op.f('ix_studyset_studies_study_id'), 'studyset_studies', ['study_id'], unique=False)
    op.create_index(op.f('ix_studyset_studies_studyset_id'), 'studyset_studies', ['studyset_id'], unique=False)
    op.create_index(op.f('ix_studysets_id'), 'studysets', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_studysets_id'), table_name='studysets')
    op.drop_index(op.f('ix_studyset_studies_studyset_id'), table_name='studyset_studies')
    op.drop_index(op.f('ix_studyset_studies_study_id'), table_name='studyset_studies')
    op.drop_index(op.f('ix_studies_id'), table_name='studies')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_points_id'), table_name='points')
    op.drop_index(op.f('ix_point_values_id'), table_name='point_values')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_index(op.f('ix_annotations_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotation_analyses_annotation_id'), table_name='annotation_analyses')
    op.drop_index(op.f('ix_annotation_analyses_analysis_id'), table_name='annotation_analyses')
    op.drop_index(op.f('ix_analysis_conditions_condition_id'), table_name='analysis_conditions')
    op.drop_index(op.f('ix_analysis_conditions_analysis_id'), table_name='analysis_conditions')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    # ### end Alembic commands ###
