"""empty message

Revision ID: 45092b0eefc8
Revises: f2337d9c250c
Create Date: 2026-01-21 19:33:45.212051

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import neurostore.models.migration_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45092b0eefc8'
down_revision = 'f2337d9c250c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('study_dependent', sa.Boolean(), nullable=True),
    sa.Column('ace_compatible', sa.Boolean(), nullable=True),
    sa.Column('pubget_compatible', sa.Boolean(), nullable=True),
    sa.Column('derived_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipelines_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipelines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipelines_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_pipelines_updated_at'), ['updated_at'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_updated_at'), ['updated_at'], unique=False)

    op.create_table('users',
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)

    op.create_table('base_studies',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('publication', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('pmid', sa.String(), nullable=True),
    sa.Column('pmcid', sa.String(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_oa', sa.Boolean(), nullable=True),
    sa.Column('has_coordinates', sa.Boolean(), nullable=False),
    sa.Column('has_images', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('ace_fulltext', sa.Text(), nullable=True),
    sa.Column('pubget_fulltext', sa.Text(), nullable=True),
    sa.Column('__ts_vector__', neurostore.models.migration_types.TSVector(), sa.Computed("\n            setweight(to_tsvector('english', coalesce(name, '')), 'A') ||\n            setweight(to_tsvector('english', coalesce(description, '')), 'B') ||\n            setweight(to_tsvector('english',\n                coalesce(\n                    CASE\n                        WHEN pubget_fulltext IS NOT NULL THEN pubget_fulltext\n                        ELSE ace_fulltext\n                    END,\n                    ''\n                )\n            ), 'C')\n            ", persisted=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("doi ~ '^(?=.*\\S).+$' OR name IS NULL"),
    sa.CheckConstraint("level IN ('group', 'meta')"),
    sa.CheckConstraint("pmid ~ '^(?=.*\\S).+$' OR name IS NULL"),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi', 'pmid', name='doi_pmid')
    )
    with op.batch_alter_table('base_studies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_base_studies_authors'), ['authors'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_studies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_studies_doi'), ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_studies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_studies_pmcid'), ['pmcid'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_studies_pmid'), ['pmid'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_studies_publication'), ['publication'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_studies_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_studies_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_studies_year'), ['year'], unique=False)
        batch_op.create_index('ix_base_study___ts_vector__', ['__ts_vector__'], unique=False, postgresql_using='gin')

    op.create_table('conditions',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conditions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conditions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conditions_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conditions_user_id'), ['user_id'], unique=False)

    op.create_table('pipeline_configs',
    sa.Column('pipeline_id', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('config_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.Column('has_embeddings', sa.Boolean(), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_configs_config_hash'), ['config_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_configs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_configs_pipeline_id'), ['pipeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_configs_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_configs_version'), ['version'], unique=False)

    op.create_table('roles_users',
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('role_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('studysets',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('publication', sa.String(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('pmid', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('__ts_vector__', neurostore.models.migration_types.TSVector(), sa.Computed("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studysets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studysets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_studysets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studysets_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_studysets_user_id'), ['user_id'], unique=False)

    op.create_table('annotations',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('studyset_id', sa.Text(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('note_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['studyset_id'], ['studysets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_studyset_id'), ['studyset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_user_id'), ['user_id'], unique=False)

    op.create_table('pipeline_embeddings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('config_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_study_id', sa.Text(), nullable=True),
    sa.Column('date_executed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('SUCCESS', 'FAILURE', 'ERROR', 'UNKNOWN', name='status_enum'), nullable=True),
    sa.Column('embedding', neurostore.models.migration_types.VectorType(), nullable=False),
    sa.ForeignKeyConstraint(['base_study_id'], ['base_studies.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['pipeline_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'config_id'),
    postgresql_partition_by='LIST (config_id)'
    )
    with op.batch_alter_table('pipeline_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_embeddings_base_study_id'), ['base_study_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_embeddings_config_id'), ['config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_embeddings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_embeddings_updated_at'), ['updated_at'], unique=False)

    op.create_table('pipeline_study_results',
    sa.Column('config_id', sa.Text(), nullable=True),
    sa.Column('base_study_id', sa.Text(), nullable=True),
    sa.Column('date_executed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('SUCCESS', 'FAILURE', 'ERROR', 'UNKNOWN', name='status_enum'), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['base_study_id'], ['base_studies.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['pipeline_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_study_results', schema=None) as batch_op:
        batch_op.create_index('ix_pipeline_study_results__modality', [sa.literal_column("(result_data -> 'Modality')")], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_pipeline_study_results_base_study_id'), ['base_study_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_study_results_config_id'), ['config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_study_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_study_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_study_results_updated_at'), ['updated_at'], unique=False)

    op.create_table('studies',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('publication', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('pmid', sa.String(), nullable=True),
    sa.Column('pmcid', sa.String(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('base_study_id', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('__ts_vector__', neurostore.models.migration_types.TSVector(), sa.Computed("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("doi ~ '^(?=.*\\S).+$' OR name IS NULL"),
    sa.CheckConstraint("level IN ('group', 'meta')"),
    sa.CheckConstraint("pmid ~ '^(?=.*\\S).+$' OR name IS NULL"),
    sa.ForeignKeyConstraint(['base_study_id'], ['base_studies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studies_authors'), ['authors'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_base_study_id'), ['base_study_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_doi'), ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_pmcid'), ['pmcid'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_pmid'), ['pmid'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_publication'), ['publication'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_year'), ['year'], unique=False)
        batch_op.create_index('ix_study___ts_vector__', ['__ts_vector__'], unique=False, postgresql_using='gin')

    op.create_table('studyset_studies',
    sa.Column('study_id', sa.Text(), nullable=False),
    sa.Column('studyset_id', sa.Text(), nullable=False),
    sa.Column('curation_stub_uuid', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studyset_id'], ['studysets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'studyset_id'),
    sa.UniqueConstraint('studyset_id', 'curation_stub_uuid', name='uq_studyset_stub_uuid')
    )
    with op.batch_alter_table('studyset_studies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studyset_studies_curation_stub_uuid'), ['curation_stub_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_studyset_studies_study_id'), ['study_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studyset_studies_studyset_id'), ['studyset_id'], unique=False)

    op.create_table('tables',
    sa.Column('study_id', sa.Text(), nullable=True),
    sa.Column('t_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('footer', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 't_id', name='uq_tables_study_t_id')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tables_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tables_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tables_study_id'), ['study_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tables_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tables_user_id'), ['user_id'], unique=False)

    op.create_table('analyses',
    sa.Column('study_id', sa.Text(), nullable=True),
    sa.Column('table_id', sa.Text(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_study_id'), ['study_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_table_id'), ['table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('analysis_conditions',
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('analysis_id', sa.Text(), nullable=False),
    sa.Column('condition_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id', 'condition_id')
    )
    with op.batch_alter_table('analysis_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_conditions_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_conditions_condition_id'), ['condition_id'], unique=False)

    op.create_table('annotation_analyses',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('study_id', sa.Text(), nullable=False),
    sa.Column('studyset_id', sa.Text(), nullable=False),
    sa.Column('annotation_id', sa.Text(), nullable=False),
    sa.Column('analysis_id', sa.Text(), nullable=False),
    sa.Column('note', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id', 'studyset_id'], ['studyset_studies.study_id', 'studyset_studies.studyset_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('annotation_id', 'analysis_id')
    )
    with op.batch_alter_table('annotation_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_analyses_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_analyses_annotation_id'), ['annotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_analyses_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('entities',
    sa.Column('analysis_id', sa.Text(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("level IN ('group', 'meta')"),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_updated_at'), ['updated_at'], unique=False)

    op.create_table('images',
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('space', sa.String(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.Column('analysis_id', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('add_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_user_id'), ['user_id'], unique=False)

    op.create_table('points',
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('space', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('label_id', sa.Float(), nullable=True),
    sa.Column('analysis_id', sa.Text(), nullable=True),
    sa.Column('cluster_size', sa.Float(), nullable=True),
    sa.Column('cluster_measurement_unit', sa.String(), nullable=True),
    sa.Column('subpeak', sa.Boolean(), nullable=True),
    sa.Column('deactivation', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_deactivation'), ['deactivation'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_points_xyz', ['x', 'y', 'z'], unique=False)

    op.create_table('image_entities',
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('entity', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image'], ['images.id'], ondelete='CASCADE')
    )
    with op.batch_alter_table('image_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_entities_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_entities_image'), ['image'], unique=False)

    op.create_table('point_entities',
    sa.Column('point', sa.Text(), nullable=True),
    sa.Column('entity', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['point'], ['points.id'], ondelete='CASCADE')
    )
    with op.batch_alter_table('point_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_entities_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_entities_point'), ['point'], unique=False)

    op.create_table('point_values',
    sa.Column('point_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('point_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_values_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_values_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_values_point_id'), ['point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_values_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_values_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_values_user_id'))
        batch_op.drop_index(batch_op.f('ix_point_values_updated_at'))
        batch_op.drop_index(batch_op.f('ix_point_values_point_id'))
        batch_op.drop_index(batch_op.f('ix_point_values_id'))
        batch_op.drop_index(batch_op.f('ix_point_values_created_at'))

    op.drop_table('point_values')
    with op.batch_alter_table('point_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_entities_point'))
        batch_op.drop_index(batch_op.f('ix_point_entities_entity'))

    op.drop_table('point_entities')
    with op.batch_alter_table('image_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_entities_image'))
        batch_op.drop_index(batch_op.f('ix_image_entities_entity'))

    op.drop_table('image_entities')
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.drop_index('ix_points_xyz')
        batch_op.drop_index(batch_op.f('ix_points_user_id'))
        batch_op.drop_index(batch_op.f('ix_points_updated_at'))
        batch_op.drop_index(batch_op.f('ix_points_id'))
        batch_op.drop_index(batch_op.f('ix_points_deactivation'))
        batch_op.drop_index(batch_op.f('ix_points_created_at'))
        batch_op.drop_index(batch_op.f('ix_points_analysis_id'))

    op.drop_table('points')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_user_id'))
        batch_op.drop_index(batch_op.f('ix_images_updated_at'))
        batch_op.drop_index(batch_op.f('ix_images_id'))
        batch_op.drop_index(batch_op.f('ix_images_created_at'))
        batch_op.drop_index(batch_op.f('ix_images_analysis_id'))

    op.drop_table('images')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_updated_at'))
        batch_op.drop_index(batch_op.f('ix_entities_id'))
        batch_op.drop_index(batch_op.f('ix_entities_created_at'))
        batch_op.drop_index(batch_op.f('ix_entities_analysis_id'))

    op.drop_table('entities')
    with op.batch_alter_table('annotation_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_analyses_updated_at'))
        batch_op.drop_index(batch_op.f('ix_annotation_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_annotation_analyses_annotation_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_analyses_analysis_id'))

    op.drop_table('annotation_analyses')
    with op.batch_alter_table('analysis_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_conditions_condition_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_conditions_analysis_id'))

    op.drop_table('analysis_conditions')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_updated_at'))
        batch_op.drop_index(batch_op.f('ix_analyses_table_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_study_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_created_at'))

    op.drop_table('analyses')
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tables_user_id'))
        batch_op.drop_index(batch_op.f('ix_tables_updated_at'))
        batch_op.drop_index(batch_op.f('ix_tables_study_id'))
        batch_op.drop_index(batch_op.f('ix_tables_id'))
        batch_op.drop_index(batch_op.f('ix_tables_created_at'))

    op.drop_table('tables')
    with op.batch_alter_table('studyset_studies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studyset_studies_studyset_id'))
        batch_op.drop_index(batch_op.f('ix_studyset_studies_study_id'))
        batch_op.drop_index(batch_op.f('ix_studyset_studies_curation_stub_uuid'))

    op.drop_table('studyset_studies')
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.drop_index('ix_study___ts_vector__', postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_studies_year'))
        batch_op.drop_index(batch_op.f('ix_studies_user_id'))
        batch_op.drop_index(batch_op.f('ix_studies_updated_at'))
        batch_op.drop_index(batch_op.f('ix_studies_source_id'))
        batch_op.drop_index(batch_op.f('ix_studies_source'))
        batch_op.drop_index(batch_op.f('ix_studies_publication'))
        batch_op.drop_index(batch_op.f('ix_studies_pmid'))
        batch_op.drop_index(batch_op.f('ix_studies_pmcid'))
        batch_op.drop_index(batch_op.f('ix_studies_id'))
        batch_op.drop_index(batch_op.f('ix_studies_doi'))
        batch_op.drop_index(batch_op.f('ix_studies_created_at'))
        batch_op.drop_index(batch_op.f('ix_studies_base_study_id'))
        batch_op.drop_index(batch_op.f('ix_studies_authors'))

    op.drop_table('studies')
    with op.batch_alter_table('pipeline_study_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_study_results_updated_at'))
        batch_op.drop_index(batch_op.f('ix_pipeline_study_results_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_study_results_created_at'))
        batch_op.drop_index(batch_op.f('ix_pipeline_study_results_config_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_study_results_base_study_id'))
        batch_op.drop_index('ix_pipeline_study_results__modality', postgresql_using='gin')

    op.drop_table('pipeline_study_results')
    with op.batch_alter_table('pipeline_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_embeddings_updated_at'))
        batch_op.drop_index(batch_op.f('ix_pipeline_embeddings_created_at'))
        batch_op.drop_index(batch_op.f('ix_pipeline_embeddings_config_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_embeddings_base_study_id'))

    op.drop_table('pipeline_embeddings')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_user_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_annotations_studyset_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_created_at'))

    op.drop_table('annotations')
    with op.batch_alter_table('studysets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studysets_user_id'))
        batch_op.drop_index(batch_op.f('ix_studysets_updated_at'))
        batch_op.drop_index(batch_op.f('ix_studysets_id'))
        batch_op.drop_index(batch_op.f('ix_studysets_created_at'))

    op.drop_table('studysets')
    op.drop_table('roles_users')
    with op.batch_alter_table('pipeline_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_configs_version'))
        batch_op.drop_index(batch_op.f('ix_pipeline_configs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_pipeline_configs_pipeline_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_configs_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_configs_created_at'))
        batch_op.drop_index(batch_op.f('ix_pipeline_configs_config_hash'))

    op.drop_table('pipeline_configs')
    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conditions_user_id'))
        batch_op.drop_index(batch_op.f('ix_conditions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_conditions_id'))
        batch_op.drop_index(batch_op.f('ix_conditions_created_at'))

    op.drop_table('conditions')
    with op.batch_alter_table('base_studies', schema=None) as batch_op:
        batch_op.drop_index('ix_base_study___ts_vector__', postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_base_studies_year'))
        batch_op.drop_index(batch_op.f('ix_base_studies_user_id'))
        batch_op.drop_index(batch_op.f('ix_base_studies_updated_at'))
        batch_op.drop_index(batch_op.f('ix_base_studies_publication'))
        batch_op.drop_index(batch_op.f('ix_base_studies_pmid'))
        batch_op.drop_index(batch_op.f('ix_base_studies_pmcid'))
        batch_op.drop_index(batch_op.f('ix_base_studies_id'))
        batch_op.drop_index(batch_op.f('ix_base_studies_doi'))
        batch_op.drop_index(batch_op.f('ix_base_studies_created_at'))
        batch_op.drop_index(batch_op.f('ix_base_studies_authors'))

    op.drop_table('base_studies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))
        batch_op.drop_index(batch_op.f('ix_roles_created_at'))

    op.drop_table('roles')
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipelines_updated_at'))
        batch_op.drop_index(batch_op.f('ix_pipelines_name'))
        batch_op.drop_index(batch_op.f('ix_pipelines_id'))
        batch_op.drop_index(batch_op.f('ix_pipelines_created_at'))

    op.drop_table('pipelines')
    # ### end Alembic commands ###
