"""empty message

Revision ID: 4c6c2af3c093
Revises: 254903f54601
Create Date: 2025-08-21 22:14:23.717438

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import neurostore.models.migration_types


# revision identifiers, used by Alembic.
revision = "4c6c2af3c093"
down_revision = "254903f54601"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("points", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deactivation", sa.Boolean(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_points_deactivation"), ["deactivation"], unique=False
        )
        batch_op.create_index("ix_points_xyz", ["x", "y", "z"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("points", schema=None) as batch_op:
        batch_op.drop_index("ix_points_xyz")
        batch_op.drop_index(batch_op.f("ix_points_deactivation"))
        batch_op.drop_column("deactivation")

    # ### end Alembic commands ###
