"""empty message

Revision ID: 53e5db3b9f89
Revises: 9c9f3aa4b5d1
Create Date: 2026-03-13 18:27:02.409384

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import neurostore.models.migration_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53e5db3b9f89'
down_revision = '9c9f3aa4b5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasets')
    op.drop_table('oauth')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('analyses_study_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['external_id'])
        batch_op.create_foreign_key(None, 'studies', ['study_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['external_id'])

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entities_study_id_fkey'), type_='foreignkey')
        batch_op.drop_column('study_id')

    with op.batch_alter_table('image_entities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('image_entities_image_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('image_entities_entity_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'images', ['image'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'entities', ['entity'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('images_analysis_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['external_id'])
        batch_op.create_foreign_key(None, 'analyses', ['analysis_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('point_entities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('point_entities_entity_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('point_entities_point_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entities', ['entity'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'points', ['point'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('point_values', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               postgresql_using="value::double precision",
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('point_values_point_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['external_id'])
        batch_op.create_foreign_key(None, 'points', ['point_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('points_analysis_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['external_id'])
        batch_op.create_foreign_key(None, 'analyses', ['analysis_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.alter_column('metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('studies_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['external_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('studies_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('metadata_',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('points_analysis_id_fkey'), 'analyses', ['analysis_id'], ['id'])

    with op.batch_alter_table('point_values', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('point_values_point_id_fkey'), 'points', ['point_id'], ['id'])
        batch_op.alter_column('value',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('point_entities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('point_entities_point_fkey'), 'points', ['point'], ['id'])
        batch_op.create_foreign_key(batch_op.f('point_entities_entity_fkey'), 'entities', ['entity'], ['id'])

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('images_analysis_id_fkey'), 'analyses', ['analysis_id'], ['id'])

    with op.batch_alter_table('image_entities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('image_entities_entity_fkey'), 'entities', ['entity'], ['id'])
        batch_op.create_foreign_key(batch_op.f('image_entities_image_fkey'), 'images', ['image'], ['id'])

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_id', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('entities_study_id_fkey'), 'studies', ['study_id'], ['id'])

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('analyses_study_id_fkey'), 'studies', ['study_id'], ['id'])

    op.create_table('oauth',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('token', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider_user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('oauth_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_pkey')),
    sa.UniqueConstraint('provider_user_id', name=op.f('oauth_provider_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('datasets',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('publication', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('doi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pmid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nimads_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('datasets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('datasets_pkey'))
    )
    # ### end Alembic commands ###
