"""empty message

Revision ID: 5620f4c0981a
Revises: 43b6caa42fae
Create Date: 2023-07-16 20:24:49.231016

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import neurostore.models.migration_types


# revision identifiers, used by Alembic.
revision = '5620f4c0981a'
down_revision = '43b6caa42fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('table_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'table_id')
    # ### end Alembic commands ###
