"""empty message

Revision ID: 6238aa82fe93
Revises: bac118d70b0f
Create Date: 2023-06-02 18:13:27.173587

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "6238aa82fe93"
down_revision = "bac118d70b0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("point_values", "dtype")
    op.add_column("points", sa.Column("cluster_size", sa.Float(), nullable=True))
    op.add_column("points", sa.Column("subpeak", sa.Boolean(), nullable=True))
    op.add_column("points", sa.Column("order", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("points", "order")
    op.drop_column("points", "subpeak")
    op.drop_column("points", "cluster_size")
    op.add_column(
        "point_values",
        sa.Column("dtype", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
