"""empty message

Revision ID: 80c3f493af81
Revises: e4d5f6a7b8c9
Create Date: 2026-02-13 17:16:20.974402

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils  # noqa: F401
import neurostore.models.migration_types  # noqa: F401


# revision identifiers, used by Alembic.
revision = "80c3f493af81"
down_revision = "e4d5f6a7b8c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.alter_column(
            "table_id",
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            existing_nullable=True,
        )

    with op.batch_alter_table("base_studies", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_base_studies_has_beta_variance_true_created_at_id"),
            postgresql_where=(
                "((has_beta_and_variance_maps IS TRUE) AND (is_active IS TRUE))"
            ),
        )
        batch_op.drop_index(
            batch_op.f("ix_base_studies_has_images_true_created_at_id"),
            postgresql_where="((has_images IS TRUE) AND (is_active IS TRUE))",
        )
        batch_op.drop_index(
            batch_op.f("ix_base_studies_has_t_maps_true_created_at_id"),
            postgresql_where="((has_t_maps IS TRUE) AND (is_active IS TRUE))",
        )
        batch_op.drop_index(
            batch_op.f("ix_base_studies_has_z_maps_true_created_at_id"),
            postgresql_where="((has_z_maps IS TRUE) AND (is_active IS TRUE))",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_base_studies_superseded_by"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "base_studies", ["superseded_by"], ["id"])

    with op.batch_alter_table("base_study_flag_outbox", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_base_study_flag_outbox_updated_at_base_study_id")
        )

    with op.batch_alter_table("base_study_metadata_outbox", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_base_study_metadata_outbox_updated_at_base_study_id")
        )

    with op.batch_alter_table("studyset_studies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_studyset_studies_curation_stub_uuid"),
            ["curation_stub_uuid"],
            unique=False,
        )

    with op.batch_alter_table("tables", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tables_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tables_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tables_updated_at"), ["updated_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tables", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tables_updated_at"))
        batch_op.drop_index(batch_op.f("ix_tables_id"))
        batch_op.drop_index(batch_op.f("ix_tables_created_at"))

    with op.batch_alter_table("studyset_studies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_studyset_studies_curation_stub_uuid"))

    with op.batch_alter_table("base_study_metadata_outbox", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_base_study_metadata_outbox_updated_at_base_study_id"),
            ["updated_at", "base_study_id"],
            unique=False,
        )

    with op.batch_alter_table("base_study_flag_outbox", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_base_study_flag_outbox_updated_at_base_study_id"),
            ["updated_at", "base_study_id"],
            unique=False,
        )

    with op.batch_alter_table("base_studies", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_base_studies_superseded_by"),
            "base_studies",
            ["superseded_by"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_index(
            batch_op.f("ix_base_studies_has_z_maps_true_created_at_id"),
            ["created_at", "id"],
            unique=False,
            postgresql_where="((has_z_maps IS TRUE) AND (is_active IS TRUE))",
        )
        batch_op.create_index(
            batch_op.f("ix_base_studies_has_t_maps_true_created_at_id"),
            ["created_at", "id"],
            unique=False,
            postgresql_where="((has_t_maps IS TRUE) AND (is_active IS TRUE))",
        )
        batch_op.create_index(
            batch_op.f("ix_base_studies_has_images_true_created_at_id"),
            ["created_at", "id"],
            unique=False,
            postgresql_where="((has_images IS TRUE) AND (is_active IS TRUE))",
        )
        batch_op.create_index(
            batch_op.f("ix_base_studies_has_beta_variance_true_created_at_id"),
            ["created_at", "id"],
            unique=False,
            postgresql_where=(
                "((has_beta_and_variance_maps IS TRUE) AND (is_active IS TRUE))"
            ),
        )

    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.alter_column(
            "table_id",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
