"""empty message

Revision ID: 87ce509ca7ba
Revises: d57ca7b74294
Create Date: 2024-02-27 20:46:20.368652

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import neurostore.models.migration_types


# revision identifiers, used by Alembic.
revision = "87ce509ca7ba"
down_revision = "d57ca7b74294"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analyses", sa.Column("order", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "order")
    # ### end Alembic commands ###
