"""empty message

Revision ID: 9f072fcaec39
Revises: 0563a23d63eb
Create Date: 2025-10-31 18:37:51.242150

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import neurostore.models.migration_types


# revision identifiers, used by Alembic.
revision = '9f072fcaec39'
down_revision = '0563a23d63eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_studies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_oa', sa.Boolean(), nullable=True))

    with op.batch_alter_table('pipeline_study_results', schema=None) as batch_op:
        batch_op.create_index('ix_pipeline_study_results__modality', [sa.literal_column("(result_data -> 'Modality')")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_study_results', schema=None) as batch_op:
        batch_op.drop_index('ix_pipeline_study_results__modality', postgresql_using='gin')

    with op.batch_alter_table('base_studies', schema=None) as batch_op:
        batch_op.drop_column('is_oa')

    # ### end Alembic commands ###
