"""empty message

Revision ID: aba107fc6544
Revises: 55fff2b2cddc
Create Date: 2024-06-15 16:36:43.520725

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import neurostore.models.migration_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aba107fc6544'
down_revision = '55fff2b2cddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('studysets', sa.Column('__ts_vector__', neurostore.models.migration_types.TSVector(), sa.Computed("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studysets', '__ts_vector__')
    op.drop_column('analyses', 'metadata_')
    # ### end Alembic commands ###
