"""empty message

Revision ID: bac118d70b0f
Revises: 44d21cfa3b0e
Create Date: 2023-05-09 21:47:42.559977

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "bac118d70b0f"
down_revision = "44d21cfa3b0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("studies", sa.Column("level", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("studies", "level")
    # ### end Alembic commands ###
