"""empty message

Revision ID: f04a2376977d
Revises: aba107fc6544
Create Date: 2025-06-16 22:49:34.124506

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import neurostore.models.migration_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f04a2376977d"
down_revision = "aba107fc6544"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipelines",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("study_dependent", sa.Boolean(), nullable=True),
        sa.Column("ace_compatible", sa.Boolean(), nullable=True),
        sa.Column("pubget_compatible", sa.Boolean(), nullable=True),
        sa.Column("derived_from", sa.Text(), nullable=True),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipelines_created_at"), "pipelines", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_pipelines_id"), "pipelines", ["id"], unique=False)
    op.create_index(op.f("ix_pipelines_name"), "pipelines", ["name"], unique=True)
    op.create_index(
        op.f("ix_pipelines_updated_at"), "pipelines", ["updated_at"], unique=False
    )
    op.create_table(
        "pipeline_configs",
        sa.Column("pipeline_id", sa.Text(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column(
            "config_args", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config_hash", sa.String(), nullable=True),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_configs_config_hash"),
        "pipeline_configs",
        ["config_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_configs_created_at"),
        "pipeline_configs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_configs_id"), "pipeline_configs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_configs_pipeline_id"),
        "pipeline_configs",
        ["pipeline_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_configs_updated_at"),
        "pipeline_configs",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_configs_version"),
        "pipeline_configs",
        ["version"],
        unique=False,
    )
    op.create_table(
        "pipeline_study_results",
        sa.Column("config_id", sa.Text(), nullable=True),
        sa.Column("base_study_id", sa.Text(), nullable=True),
        sa.Column("date_executed", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "result_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "file_inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "FAILURE", "ERROR", "UNKNOWN", name="status_enum"),
            nullable=True,
        ),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_study_id"],
            ["base_studies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["config_id"], ["pipeline_configs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_study_results_base_study_id"),
        "pipeline_study_results",
        ["base_study_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_study_results_config_id"),
        "pipeline_study_results",
        ["config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_study_results_created_at"),
        "pipeline_study_results",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_study_results_id"),
        "pipeline_study_results",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_study_results_updated_at"),
        "pipeline_study_results",
        ["updated_at"],
        unique=False,
    )
    op.add_column("base_studies", sa.Column("ace_fulltext", sa.Text(), nullable=True))
    op.add_column(
        "base_studies", sa.Column("pubget_fulltext", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("base_studies", "pubget_fulltext")
    op.drop_column("base_studies", "ace_fulltext")
    op.drop_index(
        op.f("ix_pipeline_study_results_updated_at"),
        table_name="pipeline_study_results",
    )
    op.drop_index(
        op.f("ix_pipeline_study_results_id"), table_name="pipeline_study_results"
    )
    op.drop_index(
        op.f("ix_pipeline_study_results_created_at"),
        table_name="pipeline_study_results",
    )
    op.drop_index(
        op.f("ix_pipeline_study_results_config_id"), table_name="pipeline_study_results"
    )
    op.drop_index(
        op.f("ix_pipeline_study_results_base_study_id"),
        table_name="pipeline_study_results",
    )
    op.drop_table("pipeline_study_results")
    op.drop_index(op.f("ix_pipeline_configs_version"), table_name="pipeline_configs")
    op.drop_index(op.f("ix_pipeline_configs_updated_at"), table_name="pipeline_configs")
    op.drop_index(
        op.f("ix_pipeline_configs_pipeline_id"), table_name="pipeline_configs"
    )
    op.drop_index(op.f("ix_pipeline_configs_id"), table_name="pipeline_configs")
    op.drop_index(op.f("ix_pipeline_configs_created_at"), table_name="pipeline_configs")
    op.drop_index(
        op.f("ix_pipeline_configs_config_hash"), table_name="pipeline_configs"
    )
    op.drop_table("pipeline_configs")
    op.drop_index(op.f("ix_pipelines_updated_at"), table_name="pipelines")
    op.drop_index(op.f("ix_pipelines_name"), table_name="pipelines")
    op.drop_index(op.f("ix_pipelines_id"), table_name="pipelines")
    op.drop_index(op.f("ix_pipelines_created_at"), table_name="pipelines")
    op.drop_table("pipelines")
    # ### end Alembic commands ###
