apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    isDefault: true
    user: $__env{POSTGRES_USER}
    secureJsonData:
      password: $__env{POSTGRES_PASSWORD}
    jsonData:
      host: store-pgsql
      port: 5432
      database: $__env{POSTGRES_DB}
      sslmode: disable
