services:
  compose_nginx:
    expose:
      - "80"
    ports:
      - 81:80
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro

  compose:
    expose:
      - "8000"
    command: python -m uvicorn neurosynth_compose.core:asgi_app --host 0.0.0.0 --port 8000 --reload --reload-dir /compose/backend/neurosynth_compose --log-level debug --proxy-headers --forwarded-allow-ips ${FORWARDED_ALLOW_IPS:-*}
    restart: "no"
  
  compose_worker:
    volumes:
      - ./neurosynth_compose:/usr/local/lib/python3.14/site-packages/neurosynth_compose
