"""empty message

Revision ID: 0717f5de725b
Revises: c1fb13263539
Create Date: 2023-12-12 22:59:12.319399

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0717f5de725b'
down_revision = 'c1fb13263539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specification_conditions', sa.Column('user_id', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'specification_conditions', 'users', ['user_id'], ['external_id'])
    op.add_column('specifications', sa.Column('database_studyset', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specifications', 'database_studyset')
    op.drop_constraint(None, 'specification_conditions', type_='foreignkey')
    op.drop_column('specification_conditions', 'user_id')
    # ### end Alembic commands ###
