"""empty message

Revision ID: 164fb969f549
Revises: e1c296d89bf1
Create Date: 2023-05-18 19:15:07.407065

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '164fb969f549'
down_revision = 'e1c296d89bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta_analysis_results', sa.Column('diagnostic_table', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta_analysis_results', 'diagnostic_table')
    # ### end Alembic commands ###
