"""empty message

Revision ID: 26aa47ee8e3e
Revises: 76c16b00a2bc
Create Date: 2022-12-16 18:22:04.536097

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '26aa47ee8e3e'
down_revision = '76c16b00a2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('meta_analyses', sa.Column('project_id', sa.Text(), nullable=True))
    op.add_column('meta_analyses', sa.Column('provenance', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'meta_analyses', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meta_analyses', type_='foreignkey')
    op.drop_column('meta_analyses', 'provenance')
    op.drop_column('meta_analyses', 'project_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
