"""empty message

Revision ID: 28251f5cb6d5
Revises: 3d0fc483f06b
Create Date: 2025-10-13 19:11:58.785877

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '28251f5cb6d5'
down_revision = '3d0fc483f06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studyset_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('annotation_id', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'annotations', ['annotation_id'], ['id'])
        batch_op.create_foreign_key(None, 'studysets', ['studyset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('annotation_id')
        batch_op.drop_column('studyset_id')

    # ### end Alembic commands ###
