"""empty message

Revision ID: 3d0fc483f06b
Revises: 52eabbbdffe6
Create Date: 2025-08-21 22:16:48.621497

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3d0fc483f06b'
down_revision = '52eabbbdffe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_projects_draft'), 'projects', ['draft'], unique=False)
    op.create_index(op.f('ix_projects_public'), 'projects', ['public'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_public'), table_name='projects')
    op.drop_index(op.f('ix_projects_draft'), table_name='projects')
    # ### end Alembic commands ###
