"""empty message

Revision ID: 49a5cb9f13f2
Revises: 6297073f6fcd
Create Date: 2023-10-04 16:33:06.160009

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '49a5cb9f13f2'
down_revision = '6297073f6fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specifications', sa.Column('contrast', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specifications', 'contrast')
    # ### end Alembic commands ###
