"""empty message

Revision ID: 52eabbbdffe6
Revises: 0717f5de725b
Create Date: 2024-06-15 16:44:18.644557

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '52eabbbdffe6'
down_revision = '0717f5de725b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('draft', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'draft')
    # ### end Alembic commands ###
