"""empty message

Revision ID: 6297073f6fcd
Revises: 164fb969f549
Create Date: 2023-10-04 13:36:36.588979

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6297073f6fcd'
down_revision = '164fb969f549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('conditions'):
        op.create_table('conditions',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('name', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if not inspector.has_table('specification_conditions'):
        op.create_table('specification_conditions',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('weight', sa.Float(), nullable=True),
        sa.Column('specification_id', sa.Text(), nullable=False),
        sa.Column('condition_id', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ),
        sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], ),
        sa.PrimaryKeyConstraint('id', 'specification_id', 'condition_id')
        )
        op.create_index(op.f('ix_specification_conditions_condition_id'), 'specification_conditions', ['condition_id'], unique=False)
        op.create_index(op.f('ix_specification_conditions_specification_id'), 'specification_conditions', ['specification_id'], unique=False)
    op.drop_column('specifications', 'contrast')
    op.add_column('studyset_references', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('studyset_references', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('studysets', sa.Column('version', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studysets', 'version')
    op.drop_column('studyset_references', 'updated_at')
    op.drop_column('studyset_references', 'created_at')
    op.add_column('specifications', sa.Column('contrast', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_specification_conditions_specification_id'), table_name='specification_conditions')
    op.drop_index(op.f('ix_specification_conditions_condition_id'), table_name='specification_conditions')
    op.drop_table('specification_conditions')
    op.drop_table('conditions')
    # ### end Alembic commands ###
