"""empty message

Revision ID: 685f12e01296
Revises: 26aa47ee8e3e
Create Date: 2023-02-16 17:31:51.608961

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '685f12e01296'
down_revision = '26aa47ee8e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_analysis_results',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_analysis_id', sa.Text(), nullable=True),
    sa.Column('neurostore_id', sa.Text(), nullable=True),
    sa.Column('cli_version', sa.Text(), nullable=True),
    sa.Column('cli_args', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['meta_analysis_id'], ['meta_analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neurostore_id')
    )
    op.create_table('neurovault_collections',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('result_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['meta_analysis_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id'),
    sa.UniqueConstraint('result_id')
    )
    op.create_table('neurovault_file',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('OK', 'FAILED', 'PENDING')"),
    sa.ForeignKeyConstraint(['collection_id'], ['neurovault_collections.collection_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neurovault_file')
    op.drop_table('neurovault_collections')
    op.drop_table('meta_analysis_results')
    # ### end Alembic commands ###
