"""empty message

Revision ID: 76c16b00a2bc
Revises: 97b783775549
Create Date: 2022-06-08 19:20:52.189003

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '76c16b00a2bc'
down_revision = '97b783775549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    tables = {
        'annotation_references': lambda: op.create_table('annotation_references',
            sa.Column('id', sa.Text(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        ),
        'roles': lambda: op.create_table('roles',
            sa.Column('id', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('name', sa.Text(), nullable=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
        ),
        'studyset_references': lambda: op.create_table('studyset_references',
            sa.Column('id', sa.Text(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        ),
        'users': lambda: op.create_table('users',
            sa.Column('id', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('active', sa.Boolean(), nullable=True),
            sa.Column('name', sa.Text(), nullable=True),
            sa.Column('external_id', sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('external_id')
        ),
        'roles_users': lambda: op.create_table('roles_users',
            sa.Column('user_id', sa.Text(), nullable=True),
            sa.Column('role_id', sa.Text(), nullable=True),
            sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
        ),
        'specifications': lambda: op.create_table('specifications',
            sa.Column('id', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('type', sa.Text(), nullable=True),
            sa.Column('estimator', sa.JSON(), nullable=True),
            sa.Column('filter', sa.Text(), nullable=True),
            sa.Column('contrast', sa.JSON(), nullable=True),
            sa.Column('corrector', sa.JSON(), nullable=True),
            sa.Column('public', sa.Boolean(), nullable=True),
            sa.Column('user_id', sa.Text(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
            sa.PrimaryKeyConstraint('id')
        ),
        'studysets': lambda: op.create_table('studysets',
            sa.Column('id', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('snapshot', sa.JSON(), nullable=True),
            sa.Column('public', sa.Boolean(), nullable=True),
            sa.Column('user_id', sa.Text(), nullable=True),
            sa.Column('neurostore_id', sa.Text(), nullable=True),
            sa.ForeignKeyConstraint(['neurostore_id'], ['studyset_references.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
            sa.PrimaryKeyConstraint('id')
        ),
        'annotations': lambda: op.create_table('annotations',
            sa.Column('id', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('snapshot', sa.JSON(), nullable=True),
            sa.Column('public', sa.Boolean(), nullable=True),
            sa.Column('user_id', sa.Text(), nullable=True),
            sa.Column('neurostore_id', sa.Text(), nullable=True),
            sa.Column('internal_studyset_id', sa.Text(), nullable=True),
            sa.ForeignKeyConstraint(['internal_studyset_id'], ['studysets.id'], ),
            sa.ForeignKeyConstraint(['neurostore_id'], ['annotation_references.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
            sa.PrimaryKeyConstraint('id')
        ),
        'meta_analyses': lambda: op.create_table('meta_analyses',
            sa.Column('id', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('name', sa.Text(), nullable=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('specification_id', sa.Text(), nullable=True),
            sa.Column('internal_studyset_id', sa.Text(), nullable=True),
            sa.Column('internal_annotation_id', sa.Text(), nullable=True),
            sa.Column('user_id', sa.Text(), nullable=True),
            sa.ForeignKeyConstraint(['internal_annotation_id'], ['annotations.id'], ),
            sa.ForeignKeyConstraint(['internal_studyset_id'], ['studysets.id'], ),
            sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.external_id'], ),
            sa.PrimaryKeyConstraint('id')
        ),
    }

    for table_name, creator in tables.items():
        if not inspector.has_table(table_name):
            creator()

    # Backfill columns on existing tables to match current models.
    studyset_cols = set(col["name"] for col in inspector.get_columns("studysets")) if inspector.has_table("studysets") else set()
    if inspector.has_table("studysets"):
        if "snapshot" not in studyset_cols:
            op.add_column("studysets", sa.Column("snapshot", sa.JSON(), nullable=True))
        if "version" not in studyset_cols:
            op.add_column("studysets", sa.Column("version", sa.Text(), nullable=True))

    annotation_cols = set(col["name"] for col in inspector.get_columns("annotations")) if inspector.has_table("annotations") else set()
    if inspector.has_table("annotations"):
        if "snapshot" not in annotation_cols:
            op.add_column("annotations", sa.Column("snapshot", sa.JSON(), nullable=True))
        if "cached_studyset_id" not in annotation_cols:
            op.add_column("annotations", sa.Column("cached_studyset_id", sa.Text(), nullable=True))
            op.create_foreign_key(None, "annotations", "studysets", ["cached_studyset_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_analyses')
    op.drop_table('annotations')
    op.drop_table('studysets')
    op.drop_table('specifications')
    op.drop_table('roles_users')
    op.drop_table('users')
    op.drop_table('studyset_references')
    op.drop_table('roles')
    op.drop_table('annotation_references')
    # ### end Alembic commands ###
