"""empty message

Revision ID: e1c296d89bf1
Revises: 685f12e01296
Create Date: 2023-05-09 22:11:29.476307

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1c296d89bf1'
down_revision = '685f12e01296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neurostore_studies',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('neurostore_id', sa.Text(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('OK', 'FAILED', 'PENDING')"),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neurostore_id')
    )
    op.create_table('neurostore_analyses',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('neurostore_id', sa.Text(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('meta_analysis_id', sa.Text(), nullable=True),
    sa.Column('neurostore_study_id', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('OK', 'FAILED', 'PENDING')"),
    sa.ForeignKeyConstraint(['meta_analysis_id'], ['meta_analyses.id'], ),
    sa.ForeignKeyConstraint(['neurostore_study_id'], ['neurostore_studies.neurostore_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_analysis_id'),
    sa.UniqueConstraint('neurostore_id')
    )
    op.create_table('neurovault_files',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('space', sa.Text(), nullable=True),
    sa.Column('value_type', sa.Text(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('OK', 'FAILED', 'PENDING')"),
    sa.ForeignKeyConstraint(['collection_id'], ['neurovault_collections.collection_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.drop_table('neurovault_file')
    op.add_column('annotations', sa.Column('cached_studyset_id', sa.Text(), nullable=True))
    op.drop_constraint('annotations_internal_studyset_id_fkey', 'annotations', type_='foreignkey')
    op.create_foreign_key(None, 'annotations', 'studysets', ['cached_studyset_id'], ['id'])
    op.drop_column('annotations', 'internal_studyset_id')
    op.drop_column('annotations', 'public')
    op.add_column('meta_analyses', sa.Column('neurostore_studyset_id', sa.Text(), nullable=True))
    op.add_column('meta_analyses', sa.Column('neurostore_annotation_id', sa.Text(), nullable=True))
    op.add_column('meta_analyses', sa.Column('cached_studyset_id', sa.Text(), nullable=True))
    op.add_column('meta_analyses', sa.Column('cached_annotation_id', sa.Text(), nullable=True))
    op.add_column('meta_analyses', sa.Column('run_key', sa.Text(), nullable=True))
    op.drop_constraint('meta_analyses_internal_studyset_id_fkey', 'meta_analyses', type_='foreignkey')
    op.drop_constraint('meta_analyses_internal_annotation_id_fkey', 'meta_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'meta_analyses', 'annotations', ['cached_annotation_id'], ['id'])
    op.create_foreign_key(None, 'meta_analyses', 'annotation_references', ['neurostore_annotation_id'], ['id'])
    op.create_foreign_key(None, 'meta_analyses', 'studysets', ['cached_studyset_id'], ['id'])
    op.create_foreign_key(None, 'meta_analyses', 'studyset_references', ['neurostore_studyset_id'], ['id'])
    op.drop_column('meta_analyses', 'internal_annotation_id')
    op.drop_column('meta_analyses', 'internal_studyset_id')
    op.add_column('meta_analysis_results', sa.Column('method_description', sa.Text(), nullable=True))
    op.drop_constraint('meta_analysis_results_neurostore_id_key', 'meta_analysis_results', type_='unique')
    op.drop_column('meta_analysis_results', 'neurostore_id')
    op.add_column('projects', sa.Column('public', sa.Boolean(), nullable=True))
    op.drop_column('specifications', 'public')
    op.drop_column('studysets', 'public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studysets', sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('specifications', sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'public')
    op.add_column('meta_analysis_results', sa.Column('neurostore_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('meta_analysis_results_neurostore_id_key', 'meta_analysis_results', ['neurostore_id'])
    op.drop_column('meta_analysis_results', 'method_description')
    op.add_column('meta_analyses', sa.Column('internal_studyset_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('meta_analyses', sa.Column('internal_annotation_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'meta_analyses', type_='foreignkey')
    op.drop_constraint(None, 'meta_analyses', type_='foreignkey')
    op.drop_constraint(None, 'meta_analyses', type_='foreignkey')
    op.drop_constraint(None, 'meta_analyses', type_='foreignkey')
    op.create_foreign_key('meta_analyses_internal_annotation_id_fkey', 'meta_analyses', 'annotations', ['internal_annotation_id'], ['id'])
    op.create_foreign_key('meta_analyses_internal_studyset_id_fkey', 'meta_analyses', 'studysets', ['internal_studyset_id'], ['id'])
    op.drop_column('meta_analyses', 'run_key')
    op.drop_column('meta_analyses', 'cached_annotation_id')
    op.drop_column('meta_analyses', 'cached_studyset_id')
    op.drop_column('meta_analyses', 'neurostore_annotation_id')
    op.drop_column('meta_analyses', 'neurostore_studyset_id')
    op.add_column('annotations', sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('annotations', sa.Column('internal_studyset_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.create_foreign_key('annotations_internal_studyset_id_fkey', 'annotations', 'studysets', ['internal_studyset_id'], ['id'])
    op.drop_column('annotations', 'cached_studyset_id')
    op.create_table('neurovault_file',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exception', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['OK'::text, 'FAILED'::text, 'PENDING'::text])", name='neurovault_file_status_check'),
    sa.ForeignKeyConstraint(['collection_id'], ['neurovault_collections.collection_id'], name='neurovault_file_collection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='neurovault_file_pkey'),
    sa.UniqueConstraint('image_id', name='neurovault_file_image_id_key')
    )
    op.drop_table('neurovault_files')
    op.drop_table('neurostore_analyses')
    op.drop_table('neurostore_studies')
    op.drop_table('devices')
    # ### end Alembic commands ###
