version: "2"
services:
  nginx:
    ports:
      - "80:80"

  neurostore:
    expose:
      - "8000"
    command: /usr/local/bin/gunicorn -w 2 -b :8000 neurostore.core:app --log-level debug --timeout 300 --reload
    restart: "no"
  
  neurosynth:
    expose:
      - "8001"
    command: /usr/local/bin/gunicorn -w 2 -b :8001 neurostore.core:app --log-level debug --timeout 300 --reload
    restart: "no"