version: "2"
services:
  neurostore:
    restart: always
    build: ./neurostore
    expose:
      - "8000"
    volumes:
      - ./postgres/migrations:/migrations
      - ./:/neurostore
    command: /usr/local/bin/gunicorn -w 2 -b :8000 neurostore.core:app --log-level debug --timeout 120
    env_file:
      - .env
    container_name: neurostore
  
  neurosynth:
    restart: always
    build: ./neurosynth
    expose:
      - "8001"
    volumes:
      - ./postgres/migrations:/migrations
      - ./:/neurosynth
    command: /usr/local/bin/gunicorn -w 2 -b :8001 neurosynth.core:app --log-level debug --timeout 120
    env_file:
      - .env
    container_name: neurosynth

  nginx:
    restart: always
    build: ./nginx
    expose:
      - "80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - neurostore
      - neurosynth
    environment:
      - VIRTUAL_HOST=${V_HOST}
      - LETSENCRYPT_HOST=${V_HOST}

  pgsql:
    restart: always
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - '5432'
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  default:
    external:
      name: nginx-proxy