name: Monthly Docker Compose Build

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build store images
        working-directory: store
        run: |
          echo "Services in store/docker-compose.yml:"
          docker-compose config --services
          echo "Building all images in store/docker-compose.yml with --no-cache"
          docker-compose build --no-cache

      - name: Build compose images
        working-directory: compose
        run: |
          echo "Services in compose/docker-compose.yml:"
          docker-compose config --services
          echo "Building all images in compose/docker-compose.yml with --no-cache"
          docker-compose build --no-cache
