name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AUTH0_ACCESS_TOKEN_URL: ${{ secrets.AUTH0_ACCESS_TOKEN_URL }}
        AUTH0_AUTH_URL: ${{ secrets.AUTH0_AUTH_URL }}
        AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        NEUROVAULT_ACCESS_TOKEN: ${{ secrets.NEUROVAULT_ACCESS_TOKEN }}
        PAT: ${{ secrets.PAT }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VITE_APP_AUTH0_CLIENT_ID: ${{ secrets.VITE_APP_AUTH0_CLIENT_ID }}
        VITE_APP_AUTH0_CLIENT_SECRET: ${{ secrets.VITE_APP_AUTH0_CLIENT_SECRET }}
        VITE_APP_AUTH0_DOMAIN: ${{ secrets.VITE_APP_AUTH0_DOMAIN }}
        VITE_APP_NEUROSTORE_API_DOMAIN: ${{ secrets.VITE_APP_NEUROSTORE_API_DOMAIN }}
        VITE_APP_NEUROSYNTH_API_DOMAIN: ${{ secrets.VITE_APP_NEUROSYNTH_API_DOMAIN }}

      run: |
        echo "Writing all env variables to secrets.txt..."

        for var in \
          AUTH0_ACCESS_TOKEN_URL \
          AUTH0_AUTH_URL \
          AUTH0_BASE_URL \
          AUTH0_CLIENT_ID \
          AUTH0_CLIENT_SECRET \
          CYPRESS_RECORD_KEY \
          NEUROVAULT_ACCESS_TOKEN \
          PAT \
          SSH_PRIVATE_KEY \
          VITE_APP_AUTH0_CLIENT_ID \
          VITE_APP_AUTH0_CLIENT_SECRET \
          VITE_APP_AUTH0_DOMAIN \
          VITE_APP_NEUROSTORE_API_DOMAIN \
          VITE_APP_NEUROSYNTH_API_DOMAIN
        do
          echo "[DEBUG] Writing $var to secrets.txt"
          echo "$var=${!var}" >> secrets.txt
        done

        echo "Done writing to secrets.txt."

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
