import { render, screen } from '@testing-library/react';
import { Router } from 'react-router-dom';
import { DisplayStudiesTable } from '..';
import { StudyApiResponse } from '../../utils/api';

describe('DisplayStudiesTable Component', () => {
    const historyMock = {
        push: jest.fn(),
        location: {},
        listen: jest.fn(),
    };

    const mockStudies: StudyApiResponse[] = [
        {
            analyses: ['5CgFrbqVsKsH', '4TType6JzACT', '3qgrMH6Etutw'],
            authors:
                "Robert M. Mok, M. Clare O'Donoguhue, Nicholas E. Myers, Erin H.S. Drazich and Anna C. Nobre",
            created_at: '2021-09-14T16:01:55.799028+00:00',
            description:
                "fMRI study: selective working memory in aging\r\n\r\nMok et al (2019), Neural markers of category-based selective working memory in aging. NeuroImage.\r\nAuthors: Robert M Mok, M. Clare O'Donoghue, Nicholas E Myers, Erin H.S. Drazich, Anna Christina Nobre \r\n\r\nPublished manuscript: https://www.sciencedirect.com/science/article/pii/S1053811919302228\r\n\r\nPreprint: https://www.biorxiv.org/content/early/2018/10/05/435388\r\ndoi: https://doi.org/10.1101/435388\r\n\r\n",
            doi: '10.1016/j.neuroimage.2019.03.033',
            id: '5LMdXPD3ocgD',
            metadata: {
                acquisition_orientation: '',
                add_date: '2019-01-16T18:02:09.525616Z',
                autocorrelation_model: '',
                b0_unwarping_software: '',
                communities: [],
                contributors: '',
                coordinate_space: null,
                doi_add_date: '2019-03-28T13:36:44.306669Z',
                download_url: 'https://neurovault.org/collections/4742/download',
                echo_time: null,
                field_of_view: null,
                field_strength: null,
                flip_angle: null,
                full_dataset_url: '',
                functional_coregistered_to_structural: null,
                functional_coregistration_method: '',
                group_comparison: null,
                group_description: '',
                group_estimation_type: '',
                group_inference_type: null,
                group_model_multilevel: '',
                group_model_type: '',
                group_modeling_software: '',
                group_repeated_measures: null,
                group_repeated_measures_method: '',
                handedness: null,
                hemodynamic_response_function: '',
                high_pass_filter_method: '',
                inclusion_exclusion_criteria: '',
                interpolation_method: '',
                intersubject_registration_software: '',
                intersubject_transformation_type: null,
                intrasubject_estimation_type: '',
                intrasubject_model_type: '',
                intrasubject_modeling_software: '',
                length_of_blocks: null,
                length_of_runs: null,
                length_of_trials: '',
                matrix_size: null,
                modify_date: '2019-04-23T18:18:07.556578Z',
                motion_correction_interpolation: '',
                motion_correction_metric: '',
                motion_correction_reference: '',
                motion_correction_software: '',
                nonlinear_transform_type: '',
                number_of_experimental_units: null,
                number_of_images: 8,
                number_of_imaging_runs: null,
                number_of_rejected_subjects: null,
                nutbrain_food_choice_type: '',
                nutbrain_food_viewing_conditions: '',
                nutbrain_hunger_state: null,
                nutbrain_odor_conditions: '',
                nutbrain_taste_conditions: '',
                object_image_type: '',
                optimization: null,
                optimization_method: '',
                order_of_acquisition: null,
                order_of_preprocessing_operations: '',
                orthogonalization_description: '',
                owner: 5059,
                owner_name: 'robmok',
                paper_url: 'https://linkinghub.elsevier.com/retrieve/pii/S1053811919302228',
                parallel_imaging: '',
                private: false,
                proportion_male_subjects: null,
                pulse_sequence: '',
                quality_control: '',
                repetition_time: null,
                resampled_voxel_size: null,
                scanner_make: '',
                scanner_model: '',
                skip_distance: null,
                slice_thickness: null,
                slice_timing_correction_software: '',
                smoothing_fwhm: null,
                smoothing_type: '',
                software_package: '',
                software_version: '',
                subject_age_max: null,
                subject_age_mean: null,
                subject_age_min: null,
                target_resolution: null,
                target_template_image: '',
                transform_similarity_metric: '',
                type_of_design: null,
                url: 'https://neurovault.org/collections/4742/',
                used_b0_unwarping: null,
                used_dispersion_derivatives: null,
                used_high_pass_filter: null,
                used_intersubject_registration: null,
                used_motion_correction: null,
                used_motion_regressors: null,
                used_motion_susceptibiity_correction: null,
                used_orthogonalization: null,
                used_reaction_time_regressor: null,
                used_slice_timing_correction: null,
                used_smoothing: null,
                used_temporal_derivatives: null,
            },
            name: 'Neural markers of category-based selective working memory in aging',
            pmid: null,
            publication: 'NeuroImage',
            source: 'neurovault',
            source_id: '4742',
            source_updated_at: null,
            user: null,
        },
        {
            analyses: ['5TYEtvBFrgMk', '5gMbJgyu3Puv', '7QhXDMHBBWWF'],
            authors:
                'Konstantinos Bromis, Maria Calem, Antje A.T.S. Reinders, Steven C.R. Williams and Matthew J. Kempton',
            created_at: '2021-09-14T15:58:25.930306+00:00',
            description:
                "OBJECTIVE:\r\nThe authors conducted a comprehensive meta-analysis of MRI region-of-interest and voxel-based morphometry (VBM) studies in posttraumatic stress disorder (PTSD). Because patients have high rates of comorbid depression, an additional objective was to compare the findings to a meta-analysis of MRI studies in depression.\r\n\r\nMETHOD:\r\nThe MEDLINE database was searched for studies from 1985 through 2016. A total of 113 studies met inclusion criteria and were included in an online database. Of these, 66 were selected for the region-of-interest meta-analysis and 13 for the VBM meta-analysis. The region-of-interest meta-analysis was conducted and compared with a meta-analysis of major depressive disorder. Within the region-of-interest meta-analysis, three subanalyses were conducted that included control groups with and without trauma.\r\n\r\nRESULTS:\r\nIn the region-of-interest meta-analysis, patients with PTSD compared with all control subjects were found to have reduced brain volume, intracranial volume, and volumes of the hippocampus, insula, and anterior cingulate. PTSD patients compared with nontraumatized or traumatized control subjects showed similar changes. Traumatized compared with nontraumatized control subjects showed smaller volumes of the hippocampus bilaterally. For all regions, pooled effect sizes (Hedges' g) varied from -0.84 to 0.43, and number of studies from three to 41. The VBM meta-analysis revealed prominent volumetric reductions in the medial prefrontal cortex, including the anterior cingulate. Compared with region-of-interest data from patients with major depressive disorder, those with PTSD had reduced total brain volume, and both disorders were associated with reduced hippocampal volume.\r\n\r\nCONCLUSIONS:\r\nThe meta-analyses revealed structural brain abnormalities associated with PTSD and trauma and suggest that global brain volume reductions distinguish PTSD from major depression.",
            doi: '10.1176/appi.ajp.2018.17111199',
            id: '454RhLixbGXR',
            metadata: {
                acquisition_orientation: '',
                add_date: '2018-07-20T09:32:10.646419Z',
                autocorrelation_model: '',
                b0_unwarping_software: '',
                communities: [],
                contributors: '',
                coordinate_space: null,
                doi_add_date: '2018-07-20T09:32:10.645959Z',
                download_url: 'https://neurovault.org/collections/4045/download',
                echo_time: null,
                field_of_view: null,
                field_strength: null,
                flip_angle: null,
                full_dataset_url: 'http://www.ptsdmri.uk',
                functional_coregistered_to_structural: null,
                functional_coregistration_method: '',
                group_comparison: null,
                group_description: '',
                group_estimation_type: '',
                group_inference_type: null,
                group_model_multilevel: '',
                group_model_type: '',
                group_modeling_software: '',
                group_repeated_measures: null,
                group_repeated_measures_method: '',
                handedness: null,
                hemodynamic_response_function: '',
                high_pass_filter_method: '',
                inclusion_exclusion_criteria: '',
                interpolation_method: '',
                intersubject_registration_software: '',
                intersubject_transformation_type: null,
                intrasubject_estimation_type: '',
                intrasubject_model_type: '',
                intrasubject_modeling_software: '',
                length_of_blocks: null,
                length_of_runs: null,
                length_of_trials: '',
                matrix_size: null,
                modify_date: '2018-07-20T10:12:48.064211Z',
                motion_correction_interpolation: '',
                motion_correction_metric: '',
                motion_correction_reference: '',
                motion_correction_software: '',
                nonlinear_transform_type: '',
                number_of_experimental_units: null,
                number_of_images: 3,
                number_of_imaging_runs: null,
                number_of_rejected_subjects: null,
                nutbrain_food_choice_type: null,
                nutbrain_food_viewing_conditions: null,
                nutbrain_hunger_state: null,
                nutbrain_odor_conditions: null,
                nutbrain_taste_conditions: null,
                object_image_type: '',
                optimization: null,
                optimization_method: '',
                order_of_acquisition: null,
                order_of_preprocessing_operations: '',
                orthogonalization_description: '',
                owner: 2277,
                owner_name: 'matthew.kempton',
                paper_url: 'http://ajp.psychiatryonline.org/doi/10.1176/appi.ajp.2018.17111199',
                parallel_imaging: '',
                private: false,
                proportion_male_subjects: null,
                pulse_sequence: '',
                quality_control: '',
                repetition_time: null,
                resampled_voxel_size: null,
                scanner_make: '',
                scanner_model: '',
                skip_distance: null,
                slice_thickness: null,
                slice_timing_correction_software: '',
                smoothing_fwhm: null,
                smoothing_type: '',
                software_package: '',
                software_version: '',
                subject_age_max: null,
                subject_age_mean: null,
                subject_age_min: null,
                target_resolution: null,
                target_template_image: '',
                transform_similarity_metric: '',
                type_of_design: null,
                url: 'https://neurovault.org/collections/4045/',
                used_b0_unwarping: null,
                used_dispersion_derivatives: null,
                used_high_pass_filter: null,
                used_intersubject_registration: null,
                used_motion_correction: null,
                used_motion_regressors: null,
                used_motion_susceptibiity_correction: null,
                used_orthogonalization: null,
                used_reaction_time_regressor: null,
                used_slice_timing_correction: null,
                used_smoothing: null,
                used_temporal_derivatives: null,
            },
            name: 'Meta-Analysis of 89 Structural MRI Studies in Posttraumatic Stress Disorder and Comparison With Major Depressive Disorder',
            pmid: null,
            publication: 'American Journal of Psychiatry',
            source: 'neurovault',
            source_id: '4045',
            source_updated_at: null,
            user: null,
        },
    ];

    it('should render', () => {
        render(
            <Router history={historyMock as any}>
                <DisplayStudiesTable studies={mockStudies} />
            </Router>
        );

        const rows = screen.getAllByRole('row');

        // subtract 1 to account for the table header
        expect(rows.length - 1).toEqual(mockStudies.length);
    });

    it('should show no results', () => {
        render(
            <Router history={historyMock as any}>
                <DisplayStudiesTable studies={[]} />
            </Router>
        );
        const noResults = screen.getByText('No results');
        expect(noResults).toBeInTheDocument();
    });
});
