export const STUDY_ANALYSES_COLUMN_WIDTH = 260;
export const STUDY_ANALYSIS_TABLE_MAX_HEIGHT = 'calc(100vh - 360px)';
export const STUDY_ANALYSIS_TABLE_ROW_MIN_HEIGHT_PX = 60;

export const STUDY_UNCATEGORIZED_MAPS_COLUMN_WIDTH = { xs: '140px', md: '260px' };
export const STUDY_UNCATEGORIZED_MAPS_COLLAPSED_WIDTH = 40;
